### ISSUE TITLE
可否提供一个最新评论挂件样式参考

### ISSUE THREAD

**Issue by penndu** [lizheming/waline#103]
调出最新评论的挂件后，默认只会输出文本，排版可以说是惨不忍睹，几经调试未得到理想的效果，希望官方可以提供一个最新评论挂件样式参考，最好是可直接使用哪种，谢谢！

![image](https://user-images.githubusercontent.com/46226528/103407236-db392680-4b98-11eb-9f89-c357b0b9fe4b.png)

**Comment by lizheming** [comment]
各个网站样式不一样，给样式容易存在样式覆盖的问题。其实就是一个列表样式，正经的博客主题应该都会有定义，自己稍微改改就好。官方就暂时不提供了，之后如果有其它用户给提供比较好看的默认样式的话我们可以再议~
