### ISSUE TITLE
希望添加analytics数据转waline的功能

### ISSUE THREAD

**Issue by penndu** [lizheming/waline#104]
主题之前一直使用analytics作为访问量统计，现改为waline，希望可以将之前的数据，转为waline可支持数据，谢谢！

**Comment by lizheming** [comment]
这些数据意义都不大，自己尝试转一下吧~ 其实就是把  JSON 转成 CSV，很简单的啦~ 如果之后有小伙伴提供脚本的话我再考虑集成到官方来吧~
