### ISSUE TITLE
希望能添加郵箱模板修改

### ISSUE THREAD

**Issue by jerryc127** [lizheming/waline#106]
希望能添加郵箱模板修改
類似這些
![image](https://user-images.githubusercontent.com/16351105/103453191-35112c00-4d12-11eb-81d5-d33c63deb2cf.png)

**Comment by lizheming** [comment]
`MAIL_SUBJECT` 和 `MAIL_TEMPLATE` 都是已经支持的，具体可以见代码 https://github.com/lizheming/waline/blob/master/packages/server/src/service/notify.js#L222-L236。至于 `MAIL_SUBJECT_ADMIN` 和 `MAIL_TEMPLATE_ADMIN` 我觉得自己看无所谓了就没有开放出来，要加反正也简单就是了，如果你觉得有需要可以提个 PR。

至于为什么没有在文档中写出来，是因为这两个变量需要配置的内容都比较长，我觉得在环境变量中配置不是非常友好。所以我有在想更好的配置方法，也就导致我暂时没将他们写到文档中了。环境变量的具体配置可以参见刚才链接中官方默认的模板，使用 nunjucks 语法。如果觉得需要告知其它人的话欢迎帮忙 PR 补到文档中。

**Comment by jerryc127** [comment]
感謝回復
想知道 MAIL_TEMPLATE  裏的一些調用參數 是不是跟valine-admin一樣？

**Comment by jerryc127** [comment]
明白了

**Comment by lizheming** [comment]
不太一样，这边使用的是 nunjucks 模板语法，规则是 `{{变量名}}` 这样的。目前主要有三类数据可以使用，子评论数据 `{{self}}`, 父评论数据 `{{parent}}`和网站配置数据 `{{site}}`，具体的字段参考一下源代码中的变量试试吧，或者使用 `{{self | dump}}` 把数据的 JSON 打印出来看一下也是可以的。

**Comment by jerryc127** [comment]
的確不適合在环境变量裏寫 是🐱‍👤🐱‍👤
vercel 的所有的環境變量有大小限制，只有4KB
很容易就超了
![image](https://user-images.githubusercontent.com/16351105/103454842-c9838a80-4d22-11eb-8d24-1be78d7bcbc6.png)

**Comment by lizheming** [comment]
嗯，或许还是改成在代码中配置比较合适

**Comment by lizheming** [comment]
https://waline.js.org/server/basic.html#mailsubject 已增加代码配置选项，可以直接在代码中进行配置，效果等同于环境变量。

**Comment by real-nicholas** [comment]
请教，`MAIL_SUBJECT` 和 `MAIL_TEMPLATE` 这两个变量的自定义模版，可以在自己的 GitHub 的私有仓项目里的 index.js 文件中添加自定义模版的代码不？
如何添加？

**Comment by CCKNBC** [comment]
@real-nicholas 请注意查看文档哦

**Comment by imzql** [comment]
> https://waline.js.org/server/basic.html#mailsubject 已增加代码配置选项，可以直接在代码中进行配置，效果等同于环境变量。

作者请问可以重新给一下连接吗 链接失效了

**Comment by higoozu** [comment]
> https://waline.js.org/server/basic.html#mailsubject

链接失效了哦

**Comment by lizheming** [comment]
https://waline.js.org/reference/server/config.html#mailsubject

**Comment by ab8ing** [comment]
rc1
