### ISSUE TITLE
提示 jwt malformed  

### ISSUE THREAD

**Issue by xiyizhou** [lizheming/waline#113]
无论是在Waline  自己部署的 Vercel,还是 cloudbase 上部署后，发表评论，均提示 jwt malformed
![截屏2021-01-03 上午10 58 11](https://user-images.githubusercontent.com/55862635/103470848-c46e1c00-4db2-11eb-8e30-d1692b3cdcb8.png)
![截屏2021-01-03 上午10 58 59](https://user-images.githubusercontent.com/55862635/103470850-c637df80-4db2-11eb-9f66-880646b02ff7.png)

**Comment by lizheming** [comment]
是昨天增加登录评论带来的一个 Bug，目前 `@waline/client@0.10.2` 已修复该问题，使用 CDN 地址的话不需要处理，我这边会刷新 CDN。感谢反馈！
