### ISSUE TITLE
请教下邮件通知的配置

### ISSUE THREAD

**Issue by Hades-001** [lizheming/waline#120]
目前使用的是 sendcloud 的邮件推送，在配置邮件通知的时候发现没有指定发件邮箱和发件人的配置项，请教下在什么地方可以设置？

**Comment by lizheming** [comment]
目前没有暴露这两个的配置，我之后补充一下吧

**Comment by lizheming** [comment]
增加了 `SENDER_NAME` 和 `SENDER_EMAIL` 两个配置项，你可以升级到最新版试一下。
