### ISSUE TITLE
valine导出的文件无法转换

### ISSUE THREAD

**Issue by JaydenForYou** [lizheming/waline#125]

**Comment by JaydenForYou** [comment]
[mlXJzFh1RnS1PKCqlBOey7r8-gzGzoHsz-exportPJW9GXjI1206142112912187.tar.gz](https://github.com/lizheming/waline/files/5780083/mlXJzFh1RnS1PKCqlBOey7r8-gzGzoHsz-exportPJW9GXjI1206142112912187.tar.gz)
这是导出的文件

**Comment by lizheming** [comment]
我用你的文件试了下，导出成 CloudBase 和 CSV 都没有问题呀，这是我导出出来的。


[output.zip](https://github.com/lizheming/waline/files/5780092/output.zip)

**Comment by JaydenForYou** [comment]
官网的那个转换转换不出来==

**Comment by lizheming** [comment]
https://waline.js.org/migration/tool.html 用这个页面的可以，我之后替换下 Valine 那个页面的老的迁移工具吧。
