### ISSUE TITLE
评论框提交按钮显示文字

### ISSUE THREAD

**Issue by lei2rock** [lizheming/waline#126]
**问题描述 | Describe the bug**

https://github.com/lizheming/waline/blob/b02fa1c23f86d930e6ef10544f39ebb09c2dfc5d/packages/client/src/components/CommentBox.js#L376

这个地方是不是应该是

```js
>{ctx.locale.submit}</button> 
```

这样评论框提交按钮显示为「提交」/ Submit ，而非「回复」 / Reply

**问题网站 | Website URL**

https://blog.dlzhang.com/more/

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [ ] Vercel
    - [ ] CloudBase
    - [x] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [x] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL

**Comment by lizheming** [comment]
好的，可以帮忙提个 PR 改一下
