### ISSUE TITLE
MiniValine 计划在未来适配对@waline/vercel数据交互

### ISSUE THREAD

**Issue by MHuiG** [lizheming/waline#13]
https://github.com/MiniValine/MiniValine

真·开源

**Comment by lizheming** [comment]
先给你的项目点个赞呀~ 可以的，其实我本来也不是非常想写前端这块的，如果有人专门负责前端这块再好不过了，谢谢~

**Comment by MHuiG** [comment]
有一个不兼容的位置

https://github.com/MiniValine/MiniValine/blob/master/src/utils/fetch/waline/Bean.js#L14

这里展示数据没有问题

https://github.com/MiniValine/MiniValine/blob/master/src/utils/fetch/waline/Base.js#L105-L121

数据可以成功存入，但是因为没有pid或者是rid不合法，服务端无法输出

**Comment by lizheming** [comment]
我这边是按照 Valine 的逻辑 来的，rid 是指主评论 id，pid 是父评论 id。因为 Valine 只有二级嵌套，没有楼中楼嵌套，所以它取子评论的话直接根据 rid 来即可。
你的意思是 MiniValine 这边有楼中楼嵌套，每次都使用 pid 父评论 id 获取子评论是吗？

**Comment by MHuiG** [comment]
我整理了一下
waline

pid | string | 该条评论回复的评论 objectId
-- | -- | --
rid | string | 该条评论的根评论 objectId

minivaline这边

只有pid

获取最外层父评论（根评论，这条评论没有@任何人）的方法是查找当前页pid为空或者pid不存在的所有评论

获取子评论的方法是查找当前页pid存在的所有评论

渲染方法是先渲染根评论，然后递归遍历，依据子评论的pid.查找到父评论，渲染到父评论下方，继续递归至没有子评论

评论方法是获取被评论的父评论的objectID作为子评论的pid

不兼容原因

waline的pid必须是根评论
minivaline的pid不一定是根评论，还有可能是子评论的ObjectId

**Comment by lizheming** [comment]
waline 的 pid 不是根评论 id，rid 才是。目前的 pid 应该是能满足你的需求的，只是返回评论列表的接口因为没有楼中楼的问题所以我这边直接根据 rid 获取子评论了。你那边能否帮忙提供一下你需要返回的数据格式，我这边帮忙做一下楼中楼的数据适配即可。

**Comment by MHuiG** [comment]
暂时不用了，我把那个没用到的rid发给waline后可以获取到评论了

**Comment by lizheming** [comment]
好的，辛苦了

**Comment by MHuiG** [comment]
目前已经改完一版

https://minivaline.js.org/waline.html

**Comment by lizheming** [comment]
@MHuiG 看了下非常棒！感谢支持！等你这边出了相关文档了，我这边文档会增加一下相关的跳转，谢谢。

**Comment by lizheming** [comment]
应该是我这边重复转义的缘故，之前自己转义了一遍，然后把  Valine 的 marked 配置拷贝过来它那又处理了一次。我把我的转义去掉就正常了。

**Comment by lizheming** [comment]
https://waline.js.org/client/other.html Waline 文档增加了 MiniValine 支持的说明，并提供了个简单的 Demo

**Comment by lizheming** [comment]
目前 MiniValine 针对 Waline 的适配已经完成，该 issue 暂时关闭了。后续 MiniValine 的适配问题也还是可以在此 issue 中继续讨论~
