### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by slblog-github** [lizheming/waline#139]
**问题描述 | Describe the bug**

主题评论区无法加载Waline,控制台报错 Waline.min.js:32 TypeError: n.filter is not a function
(已将Waline排除pjax异步加载)
![image](https://user-images.githubusercontent.com/64446074/104795266-d3f45880-57e7-11eb-9b7c-68ba45d52a3d.png)

**问题网站 | Website URL**

https://blog.slqwq.cn

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [x] Vercel
    - [ ] CloudBase
    - [ ] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [x] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [ ] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL

**Comment by lizheming** [comment]
meta 配置目前是需要数组结构，你修改成这个试一下

```
meta: ['nick', 'mail', 'link']
```

**Comment by slblog-github** [comment]
> meta配置目前是需要复制结构，你修改成这个试一下
> 
> ```
> meta: ['nick', 'mail', 'link']
> ```

好的，我尝试一下

**Comment by slblog-github** [comment]
![image](https://user-images.githubusercontent.com/64446074/104795657-14a1a100-57eb-11eb-8305-61af8313fa40.png)
可以了,Thanks~

**Comment by CCKNBC** [comment]
@slblog-github 杰瑞说要看文档，和Valine不一样🌝

**Comment by slblog-github** [comment]
> @slblog-github 杰瑞说要看文档，和Valine不一样🌝

那时候准备自己弄过来
毕竟杰瑞弄的功能有点少

**Comment by slblog-github** [comment]
而且当时没看到杰瑞新增了Waline

**Comment by CCKNBC** [comment]
@slblog-github 考虑到了以后可能会有更多配置，所以就没写那么多，option配置好评

**Comment by slblog-github** [comment]
> @slblog-github 考虑到了以后可能会有更多配置，所以就没写那么多，option配置好评

我当时还不知道这是用来干啥的

**Comment by CCKNBC** [comment]
@slblog-github 虽然我也是在3.4 0就开始用，但是表白杰瑞

**Comment by slblog-github** [comment]
> @slblog-github 虽然我也是在3.4 0就开始用，但是表白杰瑞

还可行
