### ISSUE TITLE
hexo插件自动配置语言

### ISSUE THREAD

**Issue by njzjz** [lizheming/waline#145]
通过`{{ page.lang }}`读取当前页面的语言，实现waline语言和当前界面的语言保持一致

**Comment by lizheming** [comment]
`@waline/hexo-next@1.0.4` 增加了 `lang` 的默认配置，你可以试一下。

**Comment by njzjz** [comment]
需要把这行去掉：
https://github.com/lizheming/waline/blob/915309e4ff5019a1f48fab3aaa4eb6acc4d1385e/packages/hexo-next/default.yaml#L10

有了这行以后，即使`config`去掉`waline.lang`，仍会生成诸如`Object.assign({lang:'en'}, {lang:null})`，`page.lang`会被`null`覆盖。
```js
Object.assign({lang:'en'}, {lang:null})
// {lang: null}
```

**Comment by lizheming** [comment]
是的，如果需要用默认配置的话 yaml 里就不要配 lang 会更好。

**Comment by njzjz** [comment]
> 是的，如果需要用默认配置的话 yaml 里就不要配 lang 会更好。

主要问题是，插件会合并默认配置
