### ISSUE TITLE
社交登录问题

### ISSUE THREAD

**Issue by youthlql** [lizheming/waline#148]
![image](https://user-images.githubusercontent.com/49017153/106083903-3c342a00-6158-11eb-83b3-5f2f168c0693.png)
我非常确定我的账户和密码都是对的，为此我还退出github重新登录了一次。

**Comment by lizheming** [comment]
你的账号是通过 Github 登录创建的吗？如果是 Github 登录创建的账号的话密码是我随机的，你需要通过 Github 登录后进个人资料里重置一下密码。
