### ISSUE TITLE
[BUG] 后台查询评论时常返回 502

### ISSUE THREAD

**Issue by YunYouJun** [lizheming/waline#150]
**问题描述 | Describe the bug**

![image](https://user-images.githubusercontent.com/25154432/107230408-05b0b600-6a5a-11eb-863d-a97a6426d512.png)

waline 后台查询评论时常出现 502。已多次尝试退出重新登录、重新部署，问题依旧存在。
时常是指，存在偶尔的情况可以正常显示评论。

**问题网站 | Website URL**

https://www.yunyoujun.cn

waline: https://waline.yunyoujun.cn

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [x] Vercel
    - [ ] CloudBase
    - [ ] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [x] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [ ] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL

**Comment by Candinya** [comment]
Vercel 在项目页面有一个 `View Function Logs` 功能，当您打开这个页面的时候，您可以尝试触发一次 Error ，看看 Vercel 那边有没有出现报错。这个默认只会监听您打开函数日志页面之后的记录，其他的会被全部丢弃，所以您需要保持网页开启的情况下进行检测。

502 Bad Gateway 理论上是网关问题。

![image](https://user-images.githubusercontent.com/20502130/107237864-2b41bd80-6a62-11eb-9acc-15ff4fa4b680.png)

**Comment by YunYouJun** [comment]
打开的确存在很多报错，似乎主要是超时问题。

![image](https://user-images.githubusercontent.com/25154432/107238757-27fb0180-6a63-11eb-9005-c242c5edb489.png)

因为 leancloud 国内版强制绑定自定义域名，所以我绑定了位于 cloudflare 解析的 waline.yunyoujun.cn。

**Comment by Candinya** [comment]
可能是的，这边看了一下LeanCloud国内版的国际连通性，基本上可以说是惨不忍睹 😭 

Vercel个人版的后端服务器（可以在项目的 `settings/serverless-functions` 查询）我记得是在美国华盛顿的，您也许可以考虑先将数据复制到LeanCloud国际版进行尝试…？

![image](https://user-images.githubusercontent.com/20502130/107239954-562d1100-6a64-11eb-97be-b61a3fd7be37.png)

**Comment by YunYouJun** [comment]
leancloud 限制为中午 12 点前导出，之后试试。

**Comment by YunYouJun** [comment]
已迁移到国际版，测试正常。
