### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Torther** [lizheming/waline#151]
**问题描述 | Describe the bug**

在服务端点击回复可以正常发送评论，但在博客点击回复无响应
**问题网站 | Website URL**

[服务端](https://comment.torther.xyz/) [博客](https://torther.xyz/)
**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [x] Vercel
    - [ ] CloudBase
    - [ ] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [x] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [ ] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL

**Comment by lizheming** [comment]
serverURL 最后的那个 `/` 需要去掉一下
