### ISSUE TITLE
[BUG]后台无法看到GitHub后端的评论

### ISSUE THREAD

**Issue by love4taylor** [lizheming/waline#152]
**问题描述 | Describe the bug**
站内评论区添加评论后无法在管理后台看到评论，在 GitHub cvs 里确实能看到评论添加成功了。
waline 版本是 0.23.1

**问题网站 | Website URL**
[blog](https://blog.love4taylor.com/)

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [x] Vercel
    - [ ] CloudBase
    - [ ] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [ ] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL
    - [x] GitHub

**相关截图**
<img width="1146" alt="QQ20210212-150847@2x" src="https://user-images.githubusercontent.com/6081912/107739616-3e93a800-6d44-11eb-9187-cb562bcb9ee0.png">

<img width="1146" alt="QQ20210212-150834@2x" src="https://user-images.githubusercontent.com/6081912/107739613-3c314e00-6d44-11eb-880d-f26e5eda1830.png">

**Comment by lizheming** [comment]
已知问题，目前猜测可能是由于多次接口调用频繁通过接口获取数据导致。目前是建议使用 Github 仓库存储的直接使用 Excel 进行数据管理，不建议使用后台进行数据管理，同时也建议关闭前台的登录功能。
