### ISSUE TITLE
[BUG] @waline/client@0.14.7 访问量显示错误 [object]

### ISSUE THREAD

**Issue by YunYouJun** [lizheming/waline#155]
**问题描述 | Describe the bug**

[BUG] @waline/client@0.14.7 访问量显示错误 [object]

![image](https://user-images.githubusercontent.com/25154432/107868982-4ed29100-6ec4-11eb-83f0-2505910cc2da.png)

回退至 `0.14.6` 可正常显示

**问题网站 | Website URL**

https://www.yunyoujun.cn/

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [x] Vercel
    - [ ] CloudBase
    - [ ] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [x] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [ ] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL

> 今天这个特殊的日子，是寓意找到对象吗？

**Comment by Candinya** [comment]
访问统计请求的工作模式发生了改变，需要同步升级后端。
应该算是一个 Breaking Change 。

**Comment by YunYouJun** [comment]
> 访问统计请求的工作模式发生了改变，需要同步升级后端。
> 应该算是一个 Breaking Change 。

Yeah. Thanks.
