### ISSUE TITLE
[Feature Request] 为访问量统计统一文章 URL

### ISSUE THREAD

**Issue by YunYouJun** [lizheming/waline#156]
## 描述

譬如同一篇文章可以通过

```txt
https://www.yunyoujun.cn/posts/2020-summary/
https://www.yunyoujun.cn/posts/2020-summary
https://www.yunyoujun.cn/posts/2020-summary/index.html
```

进行访问，这时会分别为三个不同的 URL 创建访问量统计。

可以统一转换为只查询 `https://www.yunyoujun.cn/posts/2020-summary/` 的方式。

## 期待的行为

三个不同的链接统一访问量统计。（评论同理）

**Comment by lizheming** [comment]
可以把  path 设置成 `2020-summary`，不是用默认的 `location.pathname`。

**Comment by Candinya** [comment]
waline.pug#L7 
``` diff
    const walineConfig = !{JSON.stringify(theme.waline)}
-    walineConfig.path = window.location.pathname
    new Waline(walineConfig)
```
这一行的path可以考虑使用 Hexo 的辅助函数 `url_for(page.path)` 生成

**Comment by YunYouJun** [comment]
> waline.pug#L7
> 
> ```diff
>     const walineConfig = !{JSON.stringify(theme.waline)}
> -    walineConfig.path = window.location.pathname
>     new Waline(walineConfig)
> ```
> 
> 这一行的path可以考虑使用 Hexo 的辅助函数 `url_for(page.path)` 生成

测试 `url_for(page.path)` 得到的同样是 `/posts/2020-summary/` 与 `window.location.pathname` 结果相同。

**Comment by YunYouJun** [comment]
> > waline.pug#L7
> > ```diff
> >     const walineConfig = !{JSON.stringify(theme.waline)}
> > -    walineConfig.path = window.location.pathname
> >     new Waline(walineConfig)
> > ```
> > 
> > 
> > 这一行的path可以考虑使用 Hexo 的辅助函数 `url_for(page.path)` 生成
> 
> 测试 `url_for(page.path)` 得到的同样是 `/posts/2020-summary/` 与 `window.location.pathname` 结果相同。

我明白了，此前理解错了。

**Comment by YunYouJun** [comment]
`/xxx/`、`/xxx`、`/xxx/index.html`

不过对于网页 URL 来说，应该不会存在以上三个路径代表不同内容的情况，所以如果对默认的 `path: window.location.pathname` 增加相应的适配对其进行统一是否也是一种友好的方式？

**Comment by Candinya** [comment]
> > > waline.pug#L7
> > > ```diff
> > >     const walineConfig = !{JSON.stringify(theme.waline)}
> > > -    walineConfig.path = window.location.pathname
> > >     new Waline(walineConfig)
> > > ```
> > > 
> > > 
> > > 这一行的path可以考虑使用 Hexo 的辅助函数 `url_for(page.path)` 生成
> > 
> > 
> > 测试 `url_for(page.path)` 得到的同样是 `/posts/2020-summary/` 与 `window.location.pathname` 结果相同。
> 
> 我明白了，此前理解错了。

主要是考虑到可能会涉及站点URL变更但不想因此丢失掉数据的用户吧，如果指定成`full_url_for`就会受到域名的影响，如果直接`page.path`就可能会导致文章和页面如果重名会重复数据；但这样也有一个问题就是如果页面的生成路径修改了（例如将posts指定为`:yyyy/:mm/:dd`也会丢失数据，但这属于用户操作上的配置问题了）

**Comment by Candinya** [comment]
> `/xxx/`、`/xxx`、`/xxx/index.html`
> 
> 不过对于网页 URL 来说，应该不会存在以上三个路径代表不同内容的情况，所以如果对默认的 `path: window.location.pathname` 增加相应的适配对其进行统一是否也是一种友好的方式？

可以考虑在后端引入 URL 的规范化

**Comment by YunYouJun** [comment]
Thanks.

**Comment by lizheming** [comment]
是的，因为 Waline 的最初目的是 Valine with backend，Valine 的无缝迁移是很重要的指标，所以在客户端脚本配置项及默认值上基本都是和 Valine 一致的。在我看来，使用 URL 来作为唯一标识本就不太合理，是我的话我还是会让用户使用 slug 来作为唯一标识。
