### ISSUE TITLE
[BUG]文章阅读数统计显示不正常

### ISSUE THREAD

**Issue by lei2rock** [lizheming/waline#157]
**问题描述 | Describe the bug**

Hexo NexT 博客网址，首页文章阅读数统计显示的不是每一篇文章的阅读数，变成了首页的访问数（也就是每一篇的阅读数都一样了）；点进文章后，阅读数显示是正常的。Docker 镜像是最新版的。

**问题网站 | Website URL**

https://blog.dlzhang.com

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [ ] Vercel
    - [ ] CloudBase
    - [x] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [x] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL

**Comment by njzjz** [comment]
@lei2rock +1 我也有这个问题

**Comment by YiHui-Liu** [comment]
是Waline.min.js的问题，我将你的网站中Waline.min.js的来源修改为我自己用的之后，恢复正常
![image](https://user-images.githubusercontent.com/30190271/108722709-69f56e80-755e-11eb-877d-45eafbba494d.png)
你可以下载我的Waline.min.js进行对比：https://fox-file.oss-cn-beijing.aliyuncs.com/Waline.min.js

**Comment by lei2rock** [comment]
@YiHui-Liu 我用的是 waline 官方最新的 waline.min.js，所以既然出现了问题，这个 waline.min.js 肯定是有问题

**Comment by njzjz** [comment]
应该是https://github.com/lizheming/waline/commit/b00dc641d1602bcbb94eece73243ba26a432fd7a 的问题，`add`函数中`postVisitCount`的参数是`location.pathname`，而`show`中`fetchVisitCount`的参数是`ids.join()`
这就相当于，原来的操作是，add location.pathname & show ids.join()，现在变成了add location.pathname & show location.pathname，
在post页面，`location.pathname`和`ids.join()`是相同的，但首页是不同的。

解决方案可能有：把`location.pathname`和`ids.join()`都传到server上，或者干脆只传`ids.join()`，`location.pathname`
不过我没理解为什么add和show的参数不一样。。。不应该统一吗。。。
另外` path ? Visitor.add({serverURL, path}) : Visitor.show({serverURL});`这个好像没用，path不可能为空。

**Comment by lizheming** [comment]
@njzjz path 这块的逻辑有点问题，在于之前根据 @njzjz 反馈的需求把阅读统计和阅读展现放一块了，所以导致了现在 path 没有用了。

阅读统计需要考虑两个场景：
1. 列表页多文章统计数据展现
2. 文章页单文章统计数据展现，需要展示当前展现更新后的数据

如你所说把 location.pathname 和 ids.join() 都传过去应该是可以解决问题的，不过我还在思考有没有更好的解决方法。

**Comment by lizheming** [comment]
`@waline/client@0.14.8` 已修复该问题，感谢反馈。
