### ISSUE TITLE
[BUG] 后台筛选无反应，也无报错

### ISSUE THREAD

**Issue by jalenchuh** [lizheming/waline#158]
**问题描述 | Describe the bug**

后台筛选无反应，也无报错

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [ ] Vercel
    - [x] CloudBase
    - [ ] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [x] CloudBase
    - [ ] MongoDB
    - [ ] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL

**Comment by lizheming** [comment]
已修复，请升级到 `@waline/vercel@0.23.7` 版本，感谢反馈。
