### ISSUE TITLE
[BUG]评论链接错误

### ISSUE THREAD

**Issue by YiHui-Liu** [lizheming/waline#159]
**问题描述 | Describe the bug**

在评论后台管理界面，评论的链接点进去之后会多一个斜杠，导致点击链接之后该页面无法正常加载评论
![image](https://user-images.githubusercontent.com/30190271/108716817-8a6dfa80-7557-11eb-90b0-7f125b881347.png)
![image](https://user-images.githubusercontent.com/30190271/108716966-b1c4c780-7557-11eb-92c1-c7a154f9f1c3.png)

**问题网站 | Website URL**

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [ ] Vercel
    - [ ] CloudBase
    - [ ] Docker 
    - [x] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [x] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL

**Comment by Candinya** [comment]
![image](https://user-images.githubusercontent.com/20502130/108722185-d2901b80-755d-11eb-89f4-08b41ac714b1.png)
配置的环境变量 `SITE_URL` 后面不要跟斜杠

**Comment by YiHui-Liu** [comment]
已解决，感谢
