### ISSUE TITLE
回复评论排序错误

### ISSUE THREAD

**Issue by aaro-n** [lizheming/waline#163]
**问题描述 | Describe the bug**

当在一个网页发表评论，其他人回复时，顺序是从新到旧，需要是从旧到新。注意，当回复时显示的是从旧到新，刷新一下排序就会从新到旧

**问题网站 | Website URL**

https://waline-five.vercel.app/

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [x] Vercel
    - [ ] CloudBase
    - [x] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [x] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [x] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL
    - [ ] Github
   
**其他问题**
- 能否在前端设置“anonymous=true”情况下，获取登陆？我的意思是在前端禁止登陆的情况下，有什么办法可以让博主的回复旁边显示“博主”标签，已知的一种办法是修改数据库，但这种方法太麻烦。
- 能不能注册完管理账户后，禁止新的账户注册？无论是gust账户或管理员账户。

**Comment by lizheming** [comment]
1. 排序问题是 Bug 后续修复一下
2. 前台未登录的情况下可以在后台回复，也会显示博主标签
3. 可以，后续可以加一个环境变量设置下是否允许注册

**Comment by lizheming** [comment]
排序的问题在 `@waline/vercel@0.23.8` 已修复，感谢反馈。
