### ISSUE TITLE
[BUG]评论时间显示为审批通过的时间

### ISSUE THREAD

**Issue by ZvonimirSun** [lizheming/waline#165]
**问题描述 | Describe the bug**

MySQL后端的评论时间显示为审批通过的时间，应当是建表语句中的ON UPDATE引起，然后前端展示采用insertedAt字段作为评论时间导致。我认为前台展示时间应当为评论创建时间才对吧。

![](https://img.iszy.xyz/20210309164928.png)

**问题网站 | Website URL**

[https://www.iszy.cc/](https://www.iszy.cc/)

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [ ] Vercel
    - [ ] CloudBase
    - [x] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [x] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL
    - [ ] Github

**Comment by lizheming** [comment]
你说的对，可能是我导出结构时候的问题。已修改默认导入的数据库结构了，已导入的辛苦自行修改一下吧，感谢反馈。
