### ISSUE TITLE
[BUG]使用minivaline前端时无法显示访客量

### ISSUE THREAD

**Issue by Reilkay** [lizheming/waline#169]
**问题描述 | Describe the bug**

最新版本waline在使用minivaline前端时无法显示访客量，切换低版本（0.13.2）恢复。

**问题网站 | Website URL**

https://blog.reilkay.com

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [x] Vercel
    - [ ] CloudBase
    - [ ] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [x] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [ ] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL
    - [ ] Github

**Comment by lizheming** [comment]
嗯，中间有一个 breaking change 需要客户端适配一下，我之后看怎么修改下给 MiniValine 提个 PR 吧。

**Comment by lizheming** [comment]
`MiniValine@5.1.6` 修复了该问题，请更新一下再试试~

**Comment by Reilkay** [comment]
可以了！感谢~
