### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jalenchuh** [lizheming/waline#170]
**问题描述 | Describe the bug**
评论内容遮挡恢复按钮

**问题网站 | Website URL**
https://blog.jalenchuh.cn/about 最新一条评论

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [ ] Vercel
    - [x] CloudBase
    - [ ] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [x] CloudBase
    - [ ] MongoDB
    - [ ] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL
    - [ ] Github

**Comment by lizheming** [comment]
看了一下，这个应该是你主题的样式问题，h3 有一个 before 撑高了元素导致了遮挡，主题样式上稍微兼容下即可。
![image](https://user-images.githubusercontent.com/424491/111404079-1fa08100-8709-11eb-9fd8-ebf59996876b.png)
