### ISSUE TITLE
anonymous配置项默认值建议改为null

### ISSUE THREAD

**Issue by rama291041610** [lizheming/waline#171]
类型 ： `Boolean`
默认值设置为空字符串感觉不太合理，null会更合理一些

**Comment by lizheming** [comment]
https://github.com/lizheming/waline/blob/e791a47dba057600ed0edc6e061672ae52bf0b7b/packages/client/src/components/CommentBox.js#L290

你看代码会发现其实你说的 null 和空字符串都是可以的。

**Comment by rama291041610** [comment]
> https://github.com/lizheming/waline/blob/e791a47dba057600ed0edc6e061672ae52bf0b7b/packages/client/src/components/CommentBox.js#L290
> 
> 你看代码会发现其实你说的 null 和空字符串都是可以的。

我发现了，但是还是觉得文档里默认值写成null更合适一些，boolean类型设置个空串作为默认值总感觉会有问题。如果通过ejs读取配置文件渲染来导入配置的话，空串+boolean实现就需要专门处理下空的情况，但是null + boolean就没有这个问题

**Comment by lizheming** [comment]
@rama291041610 你说的这个问题和 Waline 无关，是主题的问题，不管是 `null` 还是 Boolean，只要你配置这个字段，肯定是需要处理设置一个值的。你在群里反馈的 `anonymous: ,` 这个已经是 JavaScript 语法问题了，如果是 null 的话是 `anonymous: null,` 也是需要单独处理的。
