### ISSUE TITLE
【求助】如何修改首位注册者的“博主”tag

### ISSUE THREAD

**Issue by code004Accepted** [lizheming/waline#175]
如题，希望能加一些允许修改这个tag内容和颜色的功能，我好像没在langmode里面看到这个自定义的选项:(

另外顺便求一个通过环境变量或者代码来指定博客管理员的feature，方便博主有时候不在线时他/她的朋友协助管理评论。

多谢

**Comment by lizheming** [comment]
修改文案参考该 PR 配置 https://github.com/lizheming/waline/pull/118
颜色可通过自行定义 CSS 覆盖自定义

多管理员可以先让你朋友后台注册，注册完之后直接进数据表 User 里面将他的数据中的 status 字段值从 guest 修改成 administrator 即可。

**Comment by code004Accepted** [comment]
谢谢！问题已解决
