### ISSUE TITLE
[BUG]无法进入管理界面 Error: Illegal argument null

### ISSUE THREAD

**Issue by ichenkaihua** [lizheming/waline#180]
**问题描述 | Describe the bug**

打开`<server_url>/ui`,输入账户密码登录后,页面空白

发现控制台报错:
```
Error: Illegal argument null
    at e.exports (admin:15)
    at i (admin:10)
    at admin:54
    at Array.map (<anonymous>)
    at Gt (admin:54)
    at Zi (admin:31)
    at Ma (admin:31)
    at gl (admin:31)
    at cu (admin:31)
    at lu (admin:31)
```
![image](https://user-images.githubusercontent.com/13034364/111902950-c626b200-8a7a-11eb-9044-977fc0bb64ea.png)

**问题网站 | Website URL**

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [ ] Vercel
    - [ ] CloudBase
    - [x] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [ ] MySQL
    - [x] SQLite
    - [ ] PostgreSQL
    - [ ] Github

**Comment by lizheming** [comment]
我这用 Chrome 最新版试了一下没有问题，可以换个浏览器试试，看看是否是浏览器兼容性的问题。

**Comment by ichenkaihua** [comment]
> https://waline.chenkaihua.com/ui 我这用 Chrome 最新版试了一下没有问题，可以换个浏览器试试，看看是否是浏览器兼容性的问题。

登录没有问题，登录成功后才出现那个错误

我的chrome版本是:`89.0.4389.90`
我现在备份了评论文件，修改了密码，所以可以放心测试
账号是:`admin@chenkaihua.com`
密码是:`test1234`

**Comment by lizheming** [comment]
你的数据里 email 为 null 导致了报错，目前已经适配了，清一下浏览器缓存就可以了，感谢反馈。

**Comment by ichenkaihua** [comment]
> 你的数据里 email 为 null 导致了报错，目前已经适配了，清一下浏览器缓存就可以了，感谢反馈。

不用客气，应该的。感谢你的作品，非常好用！
