### ISSUE TITLE
是不是有毛病啊,在我博客里瞎鸡巴刷广告.有病啊!!!!!

### ISSUE THREAD

**Issue by Fantasy9527** [lizheming/waline#19]
是不是有毛病啊,在我博客里瞎鸡巴刷广告.有病啊!!!!!

**Comment by lizheming** [comment]
再次声明下，垃圾评论的事情不是我做的，我没时间也没必要这么做，而且真要做也没那么傻留下自己的信息在上面。已经在微信，博客的评论中都回复你了，具体的我就不多说了，issue 我就关闭了，感谢理解。
