### ISSUE TITLE
关于搜索功能

### ISSUE THREAD

**Issue by 888haobing** [lizheming/waline#193]
**评论管理页的搜索功能无法使用**

- 服务部署在哪里？ | Where your waline deploy?
    - [x] Vercel
    - [ ] CloudBase
    - [ ] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [ ] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL
    - [ ] Github

**Comment by lizheming** [comment]
我在官网后台测试了一下，没有问题。看了下更新日志，应该3月6日已经修复了该问题了 https://github.com/lizheming/waline/blob/master/CHANGELOG.md#2021-03-06。如若你还有问题可以试试清楚下缓存再看看。
