### ISSUE TITLE
[BUG] MySQL 存储 Emoji 展示有问题

### ISSUE THREAD

**Issue by lizheming** [lizheming/waline#197]
**问题描述 | Describe the bug**

Emoji 无法正常展示

**问题网站 | Website URL**

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [x] Vercel
    - [ ] CloudBase
    - [ ] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [x] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL
    - [ ] Github

**Comment by ichenkaihua** [comment]
@lizheming 之前配置过，貌似不支持mysql8，最后使用了sqlite

**Comment by lizheming** [comment]
> @lizheming 之前配置过，貌似不支持mysql8，最后使用了sqlite

MySQL 8 的支持需要修改默认的加密连接方式 https://zach.vip/server/mysql8-0默认加密连接方式修改/

然后将数据的表的字符集修改为 utf8mb4 并添加 MYSQL_ENCODING=utf8mb4 应该就行。

**Comment by SakuragawaAsaba** [comment]
> 然后将数据的表的字符集修改为 utf8mb4 并添加 MYSQL_ENCODING=utf8mb4 应该就行。

`MYSQL_ENCODING` 環境變數最後會給 `mysql` 傳遞 `encoding: utf8mb4` 參數，但在 `mysql` 的文檔中並無此參數，是否應使用 c`harset: UTF8_GENERAL_CI`？

> `charset`: The charset for the connection. This is called "collation" in the SQL-level
  of MySQL (like `utf8_general_ci`). If a SQL-level charset is specified (like `utf8mb4`)
  then the default collation for that charset is used. (Default: `'UTF8_GENERAL_CI'`)

(Ref: https://github.com/mysqljs/mysql/tree/v2.16.0#connection-options)

**Comment by lizheming** [comment]
> > 然后将数据的表的字符集修改为 utf8mb4 并添加 MYSQL_ENCODING=utf8mb4 应该就行。
> 
> 
> 
> `MYSQL_ENCODING` 環境變數最後會給 `mysql` 傳遞 `encoding: utf8mb4` 參數，但在 `mysql` 的文檔中並無此參數，是否應使用 `charset: UTF8_GENERAL_CI`？
> 
> 
> 
> > `charset`: The charset for the connection. This is called "collation" in the SQL-level
> 
>   of MySQL (like `utf8_general_ci`). If a SQL-level charset is specified (like `utf8mb4`)
> 
>   then the default collation for that charset is used. (Default: `'UTF8_GENERAL_CI'`)
> 
> 
> 
> (Ref: https://github.com/mysqljs/mysql/tree/v2.16.0#connection-options)
> 
> 
> 
> 

![image](https://user-images.githubusercontent.com/424491/114896262-c419fe00-9e42-11eb-876d-1760701a019b.jpeg)

文档中有说明哦，而且代码里也有定义的，看 https://github.com/mysqljs/mysql/blob/v2.16.0/lib/protocol/constants/charsets.js 倒数第二行

**Comment by SakuragawaAsaba** [comment]
> 文档中有说明哦，而且代码里也有定义的，看 [mysqljs/mysql@`v2.16.0`/lib/protocol/constants/charsets.js](https://github.com/mysqljs/mysql/blob/v2.16.0/lib/protocol/constants/charsets.js) 倒数第二行

https://github.com/lizheming/waline/blob/b96c9f0dbcc2a158c39e9933624634febb4448a0/packages/server/src/config/adapter.js#L96

我猜測問題在於應傳遞 `charset` 參數，而非目前的 `encoding` 參數。目前讀取的 `MYSQL_ENCODING` 環境變數也應變爲讀取 `MYSQL_CHARSET`。

**Comment by lizheming** [comment]
哦，这个好像是的，我明天确认下改一下。之前其他项目里好像有人反馈过。
