### ISSUE TITLE
希望增加对 Hexo NexT 主题的支持

### ISSUE THREAD

**Issue by lei2rock** [lizheming/waline#20]
希望可以去给 Hexo NexT 主题提一下 PR，增加该主题对 Waline 的支持，方便小白用户配置使用该评论系统  https://github.com/next-theme/hexo-theme-next

**Comment by MHuiG** [comment]
https://github.com/MiniValine/hexo-next-minivaline

有插件，不过前端是MiniValine的

**Comment by lizheming** [comment]
https://github.com/theme-next/hexo-theme-next/pull/1582 我这边已经提 PR 了，可能需要等那边合一下

**Comment by MHuiG** [comment]
[next-theme/hexo-theme-next#4 (comment)](https://github.com/next-theme/hexo-theme-next/issues/4#issuecomment-626205848)

**Comment by lizheming** [comment]
感谢 @MHuiG 提醒，才发现提错仓库了 https://github.com/next-theme/hexo-theme-next/pull/147 已经重新提交 PR，等待作者合并 PR 中

**Comment by lizheming** [comment]
https://www.npmjs.com/package/@waline/hexo-next 已发布 `@waline/hexo-next` 插件增加对 hexo NexT 主题的支持。

**Comment by lei2rock** [comment]
> https://www.npmjs.com/package/@waline/hexo-next 已发布 `@waline/hexo-next` 插件增加对 hexo NexT 主题的支持。

测试了一下，post-meta 会显示浏览数，但是评论数似乎不显示，需要另外设置吗？

**Comment by lizheming** [comment]
@lei2rock 插件是对着 valine 的插件改过来的，似乎是本身插件就不支持显示评论数。可能需要后期再优化下哈

**Comment by lei2rock** [comment]
> @lei2rock 插件是对着 valine 的插件改过来的，似乎是本身插件就不支持显示评论数。可能需要后期再优化下哈

嗯，Valine 那个应该也不行，似乎 NexT 显示评论数就是配置文件支持的那几个评论系统，要不然应该需要另外注入post-meta内容（NexT主题好像是有接口提供）

**Comment by lizheming** [comment]
@lei2rock 嗯，列到 todo 里之后再完善下~ 谢谢试用反馈~
