### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YinAoXiong** [lizheming/waline#200]
**问题描述 | Describe the bug**
v2ex 的域名被dns污染了，导致Gravatar头像国内无法正常加载，感觉可以加个配置项，让用户自行选择
镜像服务。

**Comment by lizheming** [comment]
https://waline.js.org/client/basic.html#avatarcdn 有的，你可以自己改一下😅

**Comment by YinAoXiong** [comment]
> https://waline.js.org/client/basic.html#avatarcdn 有的，你可以自己改一下😅

啊，打扰了，看的时候没注意到

**Comment by YiHui-Liu** [comment]
admin.js中的v2ex.com也需要改，例如https://sdn.geekzu.org/avatar/
