### ISSUE TITLE
最新評論模塊會顯示已經被屏蔽的評論

### ISSUE THREAD

**Issue by wayne0926** [lizheming/waline#204]
已经被自动或者手动标记为垃圾评论的还是会在最新评论的相关模块显示，然而在具体文章页就不会出现该评论。

**Comment by lizheming** [comment]
能否提供一下部署环境和可复现地址我测一下，目前看代码逻辑应该是把垃圾评论排除了的

**Comment by wayne0926** [comment]
> 能否提供一下部署环境和可复现地址我测一下，目前看代码逻辑应该是把垃圾评论排除了的

https://wr0926.ml/
首页的最新评论模块就是

**Comment by wayne0926** [comment]
顺带加个问题，最新评论模块的头像显示正常，但是到了文章页面头像为什么直接变成随机的了？

**Comment by jerryc127** [comment]
因为你没有使用waline的最新评论

**Comment by wayne0926** [comment]
> 因为你没有使用waline的最新评论

啊？😯这？！恩我看看类

**Comment by wayne0926** [comment]
> 因为你没有使用waline的最新评论

![Screenshot_20210419_220829_com.github.android.jpg](https://user-images.githubusercontent.com/63389859/115250105-d86c3c80-a15b-11eb-9f7d-516000131f9f.jpg)
麻烦你帮我看看，是哪里没设置对呢。
再附加一个问题🤣，那这头像怎么让文章页面显示的是用户的呢？（已经有点懵了

**Comment by jerryc127** [comment]
![Uploading image.png…]()

**Comment by jerryc127** [comment]
![image](https://user-images.githubusercontent.com/16351105/115250554-444ea500-a15c-11eb-97fb-3099caf29fcc.png)

**Comment by wayne0926** [comment]
> ![image](https://user-images.githubusercontent.com/16351105/115250554-444ea500-a15c-11eb-97fb-3099caf29fcc.png)
> 

也就是说....也许要把他全部删掉并且单独在Waline下加下级配置是吧.

**Comment by jerryc127** [comment]
不知道你说啥 反正你现在用的不是waline的最新评论就是

**Comment by wayne0926** [comment]
> 不知道你说啥 反正你现在用的不是waline的最新评论就是

好的好的。
