### ISSUE TITLE
[建议]添加评论字数要求功能

### ISSUE THREAD

**Issue by MSDNicrosoft** [lizheming/waline#206]
添加个评论字数要求功能(部署时用户可选，默认关闭)
要求最多多少字和最少多少字，两个环境变量，只要添加其中任何一项就启用此功能

**Comment by Mister-Hope** [comment]
I will take this if you would like to add this feature.

This should be added in `@waline/client` options in my opinion. @lizheming

**Comment by lizheming** [comment]
@Mister-Hope Thank you, I'm very happy to see you implement it~

**Comment by Mister-Hope** [comment]
> @Mister-Hope Thank you, I'm very happy to see you implement it~

I would like to add some unit tests when writting features, which one do you prefer? jest or mocha? I will use the one you pick.

Also I would prefer to call this option `wordLimit`, what's your opinion?

**Comment by lizheming** [comment]
@Mister-Hope OK, I'd like to use jest~ and `wordLimit` is OK, and it will work only when the value is not `undefined` and `0`.

**Comment by Mister-Hope** [comment]
I also have another question. In which way are you working on this project when not uploading version lock file and not including it in `.gitignore` at the same time? 🤣

There supposed to be a untracking version lock file in the project root by doing like this.

![image](https://user-images.githubusercontent.com/33315834/116526797-92a63580-a90c-11eb-9cba-f7f7e779e072.png)

@lizheming 

Shall they be add to `.gitignore` or just be added into the commit history?

**Comment by lizheming** [comment]
@Mister-Hope I usually use `npm` rather than `yarn`. I'm not very like lock file, so I close npm lock file config. So you can commit yarn lock file into repo, that has little effect for me.

**Comment by lizheming** [comment]
close by https://github.com/lizheming/waline/pull/219
