### ISSUE TITLE
希望添加三方Waline客户端的链接

### ISSUE THREAD

**Issue by innc11** [lizheming/waline#242]
我做了一个三方Waline客户端实现，风格偏向简洁直观一点，实现了官方客户端大部分功能，也有一些特色的地方。
本来是做给自己用的，后来想了想，不如分享给大家好了，后端应该可以不用做任何额外的配置就能迁移过去。
作者大佬能在中文文档中加入跳转链接吗，哈哈😆

项目地址：https://github.com/innc11/AprilComment

**Comment by lizheming** [comment]
非常感谢，已在文档 README 中添加说明 https://github.com/lizheming/waline/commit/05912a874fa593db2d12409889ed95e675ed1042
