### ISSUE TITLE
[BUG] 登陆后，无法自动登陆其他页面

### ISSUE THREAD

**Issue by cjh0613** [lizheming/waline#247]
**问题描述 | Describe the bug**

直接打开 https://comment.cjh0613.com/ui/login?lng=zh-cn 并登陆后，打开任意含评论页面（如 https://cjh0613.com/suiji.html ）刷新，还是显示未登陆，点击登陆，还会弹窗提示登陆

**问题网站 | Website URL**

https://cjh0613.com/suiji.html

https://comment.cjh0613.com/ui/login?lng=zh-cn

**部署方式 | Deploy Type**

Waline.min.js

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by lizheming** [comment]
你好，感谢反馈。由于前台和后台本质是两个站，所以无法做到自动关联登录状态。你可以后台使用账密登录，同时勾选记住登录。后续前台点击登录后跳转弹窗会判断已登录自动关闭弹窗并同步登录讯息到前台来。
