### ISSUE TITLE
[BUG]vercel部署出现yarn install报错

### ISSUE THREAD

**Issue by cooper1x** [lizheming/waline#248]
**问题描述 | Describe the bug**
填写三项learnCloud开发者参数后，点击deploy，出现下图报错。
![image](https://user-images.githubusercontent.com/9080789/117281923-be8a6380-ae96-11eb-8ab7-849c1b89b500.png)

GitHub我有一个新建的private仓库，但不知道找不到yarn仓库源的问题如何解决。
这应该是vercel配置的问题吧，第一次用不太了解。

**部署方式 | Deploy Type**
按照官方文档教程部署

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] 
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
这边建议亲重试.....  依赖是肯定发布了的.....

**Comment by cooper1x** [comment]
@Mister-Hope 我昨天删掉vercel 和github 项目，重新部署可以了。
