### ISSUE TITLE
评论内容包含数学公式时返回的数据不规范

### ISSUE THREAD

**Issue by innc11** [lizheming/waline#249]
如果评论内容格式为`$$公式$$+\n+其它文字`的情况下，服务端返回的数据**末尾**会附带一个空白的**结束**标签`</p>`。
如果评论内容格式为`其它文字+\n+$$公式$$`的情况下，服务端返回的数据**开头**会附带一个空白的**起始**标签`<p>`。
如果评论内容格式只包含公式`$$公式$$`则前后都没有`p`标签。

当在评论框输入以下内容并提交时
```
$$1024 \times 1024 \div 64 = 16,384$$
bbbbb
```
服务端会返回
```
<span class="katex">
    <math xmlns="http://www.w3.org/1998/Math/MathML">
        <semantics>
            <mrow>
                <mn>1024</mn>
                <mo>×</mo>
                <mn>1024</mn>
                <mo>÷</mo>
                <mn>64</mn>
                <mo>=</mo>
                <mn>16</mn>
                <mo separator="true">,</mo>
                <mn>384</mn>
            </mrow>
            <annotation encoding="application/x-tex">1024 \times 1024 \div 64 = 16,384</annotation>
        </semantics>
    </math>
</span>
bbbbb
</p>
```
这是后台界面显示的数据：
```
<p>$$1024 \times 1024 \div 64 = 16,384$$<br>bbbbb</p>
```

不过显示起来没有什么问题，只是多了一个空白的`<p></p>`，不影响其它功能

![image](https://user-images.githubusercontent.com/28993050/117383257-f636f100-af12-11eb-9e90-b2d7ab459373.png)

猜想可能是与`controller/comment.js`内的数学公式渲染相关代码有关，不过也只是一点小问题啦，影响不大

**Comment by Mister-Hope** [comment]
I will have a look when I have time. But I am not sure if it can be fixed.

The katex support is added by hacking(search with regex and render to `<math>` first), maybe there are problems when `marked` resolves a markdown content with line breaks in inline html tags. If so, it can be seen as a bug in `marked`

**Comment by lizheming** [comment]
谢谢指出，这是正则替换的时候没有使用非捕获的问题，已经处理。

**Comment by innc11** [comment]
> Thanks for the detailed infomation!!!!
> 
> I will have a look when I have time. But I am not sure if it can be fixed.
> 
> The katex support is added by hacking(search with regex and render to `<math>` first), maybe there are problems when `marked` resolves a markdown content with line breaks in inline html tags. If so, it can be seen as a bug in `marked`

Thank you for spending time on it.

**Comment by innc11** [comment]
> 谢谢指出，这是正则替换的时候没有使用非捕获的问题，已经处理。

非常感谢！
