### ISSUE TITLE
[反馈]V2EX 提供的头像镜像服务被墙

### ISSUE THREAD

**Issue by dyxang** [lizheming/waline#258]
v2ex主站于不久前被墙，所以现在的头像 cdn 也无法访问

**Comment by lizheming** [comment]
感谢反馈，已经根据之前群友的反馈替换成了 https://sdn.geekzu.org/gravatar

**Comment by lizheming** [comment]
未注意到极客族的地址是 avatar ，感谢 https://github.com/lizheming/waline/pull/259/ 已合并
