### ISSUE TITLE
> https://waline.js.org/client/basic.html#requiredfields 你把 requiredFields 设置一下吧，把 nick 设置成必填项试试

### ISSUE THREAD

**Issue by lizheming** [lizheming/waline#260]
> https://waline.js.org/client/basic.html#requiredfields 你把 requiredFields 设置一下吧，把 nick 设置成必填项试试

----
用的过程中发现个小问题，就不开新讨论了，看看后续是否有优化计划哈。

就是每次评论完，评论按钮变为禁用态之后，没有任何loading反馈，像valine评论加载时，在下方会有个loading图示。

而且不知道为什么waline生成评论的速度好像会比valine长些，我认为这样的情况下加载反馈就更重要了

_Originally posted by @tsq456 in https://github.com/lizheming/waline/discussions/179#discussioncomment-716784_

**Comment by Mister-Hope** [comment]
Loading state is added in https://github.com/lizheming/waline/commit/b9dc2c6a044dff0bfa1beb860b2c8044f7dee764

**Comment by tsq456** [comment]
> Loading state is added in [b9dc2c6](https://github.com/lizheming/waline/commit/b9dc2c6a044dff0bfa1beb860b2c8044f7dee764)

这种更新是留待下个版本发布吗？

**Comment by Mister-Hope** [comment]
> > Loading state is added in [b9dc2c6](https://github.com/lizheming/waline/commit/b9dc2c6a044dff0bfa1beb860b2c8044f7dee764)
> 
> 这种更新是留待下个版本发布吗？

Yes, after all the plans are completed

**Comment by Mister-Hope** [comment]
requiredFields is fixed.
