### ISSUE TITLE
[BUG]自定义表情无法正常显示

### ISSUE THREAD

**Issue by kawashiro-ryofu** [lizheming/waline#265]
**问题描述 | Describe the bug**

自定义表情在发送后显示的是表情的HTML标签片段，无法正常显示

**问题网站 | Website URL**

 - https://www.kawashiros.club/messageboard/
 - https://blog.xiaolfeng.cn/2021-008.html
 - https://www.senventise.com/2021/04/17/MIUI%E5%8D%81%E7%A7%92%E7%9B%BE%E7%BB%95%E8%BF%87/
 etc.

![A1](https://user-images.githubusercontent.com/53611149/117996379-b0e04c80-b374-11eb-9f57-a15a7b6aa9b5.png)

![A2](https://user-images.githubusercontent.com/53611149/117996378-b0e04c80-b374-11eb-9aac-ab496e7bd592.png)

![A3](https://user-images.githubusercontent.com/53611149/117996380-b0e04c80-b374-11eb-9880-4821e38b2b2c.png)

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [x] GitHub

**Comment by kawashiro-ryofu** [comment]
（我自己的网站是[www.kawashiros.club](https://www.kawashiros.club)。去测试了其他人的站点，发现都是同样的情况。上面出现问题的网站都是用的hexo引擎。但在官方的测试页面中没什么问题出现，原因不明）

**Comment by Mister-Hope** [comment]
Thanks for reporting!

But please remember that  you should upgrade to latest version before opening any issues in any repos.

Obviously you are not using the latest `@waline/vercel`. Please upgrade it by reploying it on vercel, or stop your application then upgrade to the latest deps and rerun it on your self hosted environment.

Feel free to reopen it if the issue still exist after upgrading to the latest version.

---

感谢您的报告！

但是请您注意，在任何存储库中的新建任何 issue 之前，应先升级到最新版本。

显然，您没有使用最新的 `@waline/vercel`。 请通过重新部署来升级它，或者在自己的托管环境中停止您的应用程序，然后升级到最新的依赖并重新运行它。

如果升级到最新版本后问题仍然存在，请随时重新打开它。

**Comment by kawashiro-ryofu** [comment]
已解决，感谢

**Comment by lei2rock** [comment]
> 已解决，感谢

怎么解决的，我也有这个问题 https://blog.dlzhang.com/more/

**Comment by guanqr** [comment]
@lei2rock 到存放 waline 部署文件的仓库中，将 `package.json` 中的 @waline/vercel 升级到最新版，然后重新部署一下就行了。

```
"@waline/vercel": "^0.24.0"
```

**Comment by eallion** [comment]
@Mister-Hope CloudBase 版也同步更新一下，谢谢！

**Comment by Mister-Hope** [comment]
> @Mister-Hope CloudBase 版也同步更新一下，谢谢！

![Screenshot_20210520-170849.jpg](https://user-images.githubusercontent.com/33315834/118952214-55bee300-b98e-11eb-9f56-e3eab9acc78c.jpg)

Cloudbase is using the latest 0.24.x

**Comment by eallion** [comment]
Sync to update walinejs/tcb-starter, plz
