### ISSUE TITLE
[BUG]手机版 requiredmeta 输入框没有边框，缺乏识别度。

### ISSUE THREAD

**Issue by eallion** [lizheming/waline#273]
**问题描述 | Describe the bug**
来自网站访客的反馈：
手机版`requiredmeta`输入框没有边框，缺乏识别度（见下图），如果不是经常逛博客的人不知道在哪里输入用户名和邮箱。

**问题网站 | Website URL**

<https://waline.js.org/>

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Vercel
  - [x] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [x] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

- 截图
![photo_2021-05-19_12-58-54](https://user-images.githubusercontent.com/1698841/118759291-4d3dae00-b8a3-11eb-9081-e646812c065e.jpg)

- iPhone6 
另外在 iPhone6 的 Safari 上，`placeholder` 排版错误，不能正确换行。

![IMG_0179](https://user-images.githubusercontent.com/1698841/118759284-4a42bd80-b8a3-11eb-9706-3dd81d05fa5e.PNG)

**Comment by Mister-Hope** [comment]
![Screenshot_20210519-135358.jpg](https://user-images.githubusercontent.com/33315834/118762981-ae688000-b8a9-11eb-9c59-bc6025c367c7.jpg)

https://html.spec.whatwg.org/multipage/input.html#the-placeholder-attribute

Line break in placeholder is NOT allowed in specification AT ALL. While some of the broswers are supporting it.

If you do meed placeholder on all devices please use

```css
textarea:not(:focus)::before{
    content: "line\nbreak"
}
```

as a hack.

**Comment by Mister-Hope** [comment]
Thanks for the advice for input appearance on mobile, new outlook is here.

![image](https://user-images.githubusercontent.com/33315834/118764681-7d3d7f00-b8ac-11eb-8b8a-1606601a2770.png)

**Comment by eallion** [comment]
gj thx!
