### ISSUE TITLE
[BUG]表情无法正常转换

### ISSUE THREAD

**Issue by penndu** [lizheming/waline#275]
**问题描述 | Describe the bug**

选择表情点击提交之后，返回的是表情链接。

**问题网站 | Website URL**

https://dusays.com/321/

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Vercel
  - [ ] CloudBase
  - [x] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [x] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by Mister-Hope** [comment]
Please use latest server. See https://github.com/lizheming/waline/issues/265
