### ISSUE TITLE
[BUG]配置telegram推送后评论报错

### ISSUE THREAD

**Issue by Editi0** [lizheming/waline#276]
**问题描述 | Describe the bug**

配置telegram推送后评论报错
```
400 - {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Character '#' is reserved and must be escaped with the preceding '\\'"}
```

**问题网站 | Website URL**

https://waline-olive.vercel.app/

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by Editi0** [comment]
发现bug原因了，`SITE_NAME`包含字符`'`会造成这个报错

**Comment by lizheming** [comment]
你好，感谢反馈，目前暂时没看出来代码层面是否有什么问题 https://github.com/lizheming/waline/blob/master/packages/server/src/service/notify.js#L165，猜测可能是因为 Telegram 的怪异 Markdown 语法导致的问题。你这边先规避一下吧，我这边收集下看看是否有类似问题，如果有的话我后期再跟进一下。目前先关闭该 issue，有后续问题我们可以继续讨论。
