### ISSUE TITLE
希望可以同步更新 CloudBase 版

### ISSUE THREAD

**Issue by eallion** [lizheming/waline#278]
- <https://github.com/lizheming/waline/tree/master/packages/cloudbase>
- <https://github.com/walinejs/tcb-starter>

thx

**Comment by lizheming** [comment]
CloudBase 官方之前反馈的是只要重新安装依赖，他们是可以根据版本规则自动安装到最新的。如果有没有更新的问题你可以给 CloudBase 那边反馈一下。目前仓库的版本号更新都是手动更新的，是提供给自动安装还没有安装到最新版留的兜底方案，暂无法做到自动同步。

**Comment by eallion** [comment]
#265 比如这个修复在 Cloudbase 版就不生效。

**Comment by Mister-Hope** [comment]
我再表述一下，cloudbase package已经是最新的依赖了，按照lizheming所说，你确保自己cloudbase上package.json依赖范围包含最新的@waline/cloudbase，重新部署就会拉取最新的0.24.x @waline/server，如果你重复这一步骤，发现线上仍然不是最新版本，请找cloudbase官方

**Comment by lizheming** [comment]
> #265 比如这个修复在 Cloudbase 版就不生效。

有升级到最新版么，按照文档说的操作一下试试 https://waline.js.org/faq.html#%E6%9C%8D%E5%8A%A1%E7%AB%AF

**Comment by eallion** [comment]
肯定试过好多次了。我还提交了 pr

**Comment by lizheming** [comment]
那你确认下版本吧，`@waline/cloudbase` 线上已经是最新的了

**Comment by JaxsonWang** [comment]
@eallion 您好，请问您的 tcb 表情包转义问题解决好了吗？我这边也有这个问题，升级waline确实是最新的，然后查看 node_modules 里面的不是最新的...请问你是咋解决的？

**Comment by eallion** [comment]
> @eallion 您好，请问您的 tcb 表情包转义问题解决好了吗？我这边也有这个问题，升级waline确实是最新的，然后查看 node_modules 里面的不是最新的...请问你是咋解决的？

Sorry，我现在在用 Twikoo。
