### ISSUE TITLE
[咨询]如何修改文章页面评论数量前的文字

### ISSUE THREAD

**Issue by tyadan** [lizheming/waline#283]
**问题描述 | Describe the bug**
如图所示，Next 主题下，在文章详情页面的评论数量前，默认显示为Waline，请问这个字符串如何修改

<img width="561" alt="Snipaste_2021-05-23_02-56-51" src="https://user-images.githubusercontent.com/13864360/119238016-9b3c0580-bb72-11eb-8557-1163dd0bd362.png">

**问题网站 | Website URL**

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Docker
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.cn)

**Comment by lizheming** [comment]
麻烦提供一下网址我看一下吧

**Comment by akuraito** [comment]
如果你使用的是最新的 next 主题 [8.4.0](https://github.com/next-theme/hexo-theme-next/releases/tag/v8.4.0) ,那么你可以在 `source` 文件夹下新建 `_data/languages.yml` 文件并填入以下内容以更改此位置的翻译。
```
zh-CN:
  post:
    comments:
      waline: 评论
```
next 主题文档已有[相关说明](https://theme-next.js.org/docs/theme-settings/internationalization.html#Override-Default-Translations)

**Comment by tyadan** [comment]
感谢，已经解决
