### ISSUE TITLE
好像只能用国际版 LeanCloud ?

### ISSUE THREAD

**Issue by eallion** [lizheming/waline#5]
好像只能用国际版 LeanCloud?
试了 Vercel 和 Docker ，国际版的可用，国内华东区的报错。忘记错误代码是什么了。

**Comment by lizheming** [comment]
国内版需要在后台绑定一个已备案域名，接口这块还需要配一下 serverURL 才行，否则接口没一会就会超限制报错。可以增加一下这块的配置项，也可以增加一下这块的文档说明。

**Comment by eallion** [comment]
<https://waline-cn.vercel.app/>  
<https://waline-test.vercel.app/>  

确实需要文档。

**Comment by lizheming** [comment]
已增加 `LEAN_SERVER` 环境变量，同时文档增加了国内版绑定域名相关的说明提示。

**Comment by eallion** [comment]
@lizheming 我看到了，我准备来提交 PR 发现你已经修改了。

**Comment by eallion** [comment]
@lizheming 你那边重新 Pull 一下 Docker 镜像，我帮你测试一下。

**Comment by eallion** [comment]
我自己 Build 的可用。

**Comment by lizheming** [comment]
@eallion docker hub 的 CI 钩子不知为何没有触发，我重新 trigger 构建了。
