### ISSUE TITLE
docker logs 错误记录

### ISSUE THREAD

**Issue by lei2rock** [lizheming/waline#50]
https://github.com/MiniValine/MiniValine/issues/248

我搬到这里讨论吧，毕竟后续和MiniValine无关。可以正常加载评论了，但是docker logs还有以下报错
![image](https://user-images.githubusercontent.com/19180725/100538157-ee3e9b00-3268-11eb-94c1-6de682e506ea.png)

**Comment by lizheming** [comment]
https://github.com/MiniValine/MiniValine/issues/248#issuecomment-735365863 这个已经回过你了

**Comment by lei2rock** [comment]
我已经拉取了最新的镜像，所以只要可以正常工作，这个错误可以忽略是吧？

**Comment by lizheming** [comment]
不好意思，刚才在外面没有仔细看截图，发现是另外一个问题。这个问题如果邮件发送正常的话你可以忽略，之后我再看一下吧。
