### ISSUE TITLE
Valine LeanCloud 数据迁移至 Cloudbase 失败

### ISSUE THREAD

**Issue by lei2rock** [lizheming/waline#51]
刚刚看到可以部署到腾讯云云开发，但是用 https://waline.js.org/migration.html#%E8%BF%81%E7%A7%BB%E8%87%B3-cloudbase 所列到转换工具时候点击转换按钮没有反应

**Comment by lizheming** [comment]
可以看下浏览器控制台是否有什么报错吗？那个脚本写的比较仓促，可能是会有些问题。

**Comment by lei2rock** [comment]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/19180725/100691246-3d004800-33c3-11eb-97f1-8ca5a37977da.png">

**Comment by lizheming** [comment]
囧了，被转义了，稍等我改一下哈

**Comment by lizheming** [comment]
@lei2rock 可以了你再试试？如果还有问题的话可以发下报错，邮件发我一下导出的 JSON 文件。

**Comment by lei2rock** [comment]
- 可以导入了，但是评论的时间似乎不能读取（使用Hexo NexT + MiniValine）。
- 此外，提交评论后加载图标会一致显示，虽然已经在页面显示成功提交和发送通知邮件了（LeanCloud下不存在该问题）。

<img width="727" alt="image" src="https://user-images.githubusercontent.com/19180725/100731045-d51f2100-3405-11eb-93c2-963085215802.png">

**Comment by lizheming** [comment]
如果方便的话能发一份你的导出 json 给我么，时间这块应该有点问题，需要处理一下。我的邮箱在个人页有，谢谢。
第二个看起来应该是 MiniValine 的问题 @MHuiG 帮忙看看吧

**Comment by MHuiG** [comment]
https://github.com/MiniValine/MiniValine/blob/master/src/utils/fetch/waline/Bean.js#L12

**Comment by MHuiG** [comment]
https://github.com/lizheming/waline/blob/master/packages/client/src/components/CommentCard.js#L24

**Comment by lizheming** [comment]
@MHuiG 你看下第二个问题吧，第一个问题应该是数据转换那有问题，我让他提供下数据看一下，和前端这块关系不大。

**Comment by MHuiG** [comment]
解决完第一个第二个就能搞定

**Comment by lizheming** [comment]
好的，那我这边先看一下

**Comment by MHuiG** [comment]
Cloudbase的返回数据里是不是没有createdAt

**Comment by MHuiG** [comment]
如果没有的话，我这边那一行得改成insertedAt

**Comment by lei2rock** [comment]
> Cloudbase的返回数据里是不是没有createdAt

全部提供评论数据涉及隐私，就提供这一条CloudBase导出数据的范例吧

``
{"_id":"2a7b532a5fc59e9400995a0e426717e2","link":"","mail":"zjzhdl@163.com","nick":"dd","ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.52","url":"/more/","ip":"223.17.186.30","insertedAt":{"$date":"2020-12-01T01:38:27.335Z"},"comment":"<p>111</p>\n","status":"approved"}
```

**Comment by lei2rock** [comment]
上述第一、第二条现在的显示效果如下
<img width="683" alt="image" src="https://user-images.githubusercontent.com/19180725/100738727-fc2f2000-3410-11eb-90a2-3a81d60d0fd5.png">

**Comment by MHuiG** [comment]
浏览器控制台下运行
new Date("2018-06-18T12:04:02.446Z")
报错吗

**Comment by lei2rock** [comment]
> 浏览器控制台下运行
> new Date("2018-06-18T12:04:02.446Z")
> 报错吗

new Date("2018-06-18T12:04:02.446Z")不会报错，但是提交评论会报错
<img width="640" alt="image" src="https://user-images.githubusercontent.com/19180725/100739710-7613d900-3412-11eb-9a6f-7760970e5751.png">

**Comment by lei2rock** [comment]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/19180725/100739816-a78ca480-3412-11eb-8d95-8c8f1478c96e.png">

**Comment by MHuiG** [comment]
为什么Nick会undefined

**Comment by MHuiG** [comment]
console.log(JSON.parse(`{"_id":{"$oid":"5b279fb29f54540035efbba5"},"nick":"Anonymous","updatedAt":"2020-11-29T00:30:36.126Z","mail":"","ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36","insertedAt":{"__type":"Date","iso":"2018-06-18T12:04:02.132Z"},"createdAt":"2018-06-18T12:04:02.446Z","isSpam":false,"status":"approved","comment":"<p>四四南村真的是信义计划区的痛</p>\n","url":"/photos/"}
`))

**Comment by lei2rock** [comment]
Edge 测试：
<img width="637" alt="image" src="https://user-images.githubusercontent.com/19180725/100742147-44e8d800-3415-11eb-8ee8-3c28dd6cb6f7.png">

**Comment by lizheming** [comment]
@lei2rock 你清一下数据重新试一下导入功能，我这边做了下数据兼容了。

**Comment by lei2rock** [comment]
> @lei2rock 你清一下数据重新试一下导入功能，我这边做了下数据兼容了。

我重新导入了数据，在CloudBase重新部署了，问题依旧

**Comment by MHuiG** [comment]
CloudBase重新部署后请求这个链接的数据是什么格式

https://**************/comment?path=/more/&pageSize=6&page=1

**Comment by lei2rock** [comment]
> CloudBase重新部署后请求这个链接的数据是什么格式
> 
> ```
> https://<serverURL>/comment?path=/more/&pageSize=6&page=1
> ```

```
{"page":1,"totalPages":4,"pageSize":6,"data":[{"nick":"Anonymous","mail":"d41d8cd98f00b204e9800998ecf8427e","insertedAt":{"__type":"Date","iso":"2020-03-28T13:03:05.854Z"},"link":"","comment":"<p>博主可以说一下文章总览的分类导航如何做吗，如果方便的话，谢谢了！</p>\n","objectId":"5e7f4b0a8fe9ac000888895b","browser":"Chrome 80.0.3987.149","os":"Mac OS 10.14.5","children":[{"nick":"班班","mail":"cc763511474fe24ffcc80257fb7cb970","insertedAt":{"__type":"Date","iso":"2020-03-28T13:05:39.912Z"},"pid":"5e7f4b0a8fe9ac000888895b","link":"","comment":"<p><a class=\"at\" href=\"#5e7f4b0a8fe9ac000888895b\">@Anonymous </a> , 分类页本来就是自动生成的呀，具体的实现你要不看看我的<a href=\"https://github.com/lei2rock/blog\">博客源代码</a>？</p>\n","rid":"5e7f4b0a8fe9ac000888895b","objectId":"5e7f4ba4743cde000806475a","browser":"Safari 13.1","os":"Mac OS 10.15.4"}]},{"nick":"Anonymous","mail":"d41d8cd98f00b204e9800998ecf8427e","insertedAt":{"__type":"Date","iso":"2020-03-18T13:35:45.201Z"},"link":"","comment":"<p>请问下博主，每篇博文在首页成卡片式展示是怎么设置的，是styles.styl中的文章页卡片吗，我借用了没有达到效果😂</p>\n","objectId":"5e7223b198a3540008f2ad6c","browser":"Firefox 74.0","os":"Windows 10","children":[{"nick":"Anonymous","mail":"d41d8cd98f00b204e9800998ecf8427e","insertedAt":{"__type":"Date","iso":"2020-03-18T14:00:42.184Z"},"pid":"5e72262598a3540008f2b089","link":"","comment":"<p><a class=\"at\" href=\"#5e72262598a3540008f2b089\">@班班 </a> , 好的，多谢班班😄</p>\n","rid":"5e7223b198a3540008f2ad6c","objectId":"5e72298a26218b00085d7963","browser":"Firefox 74.0","os":"Windows 10"},{"nick":"班班","mail":"cc763511474fe24ffcc80257fb7cb970","insertedAt":{"__type":"Date","iso":"2020-03-18T13:46:12.660Z"},"pid":"5e7223b198a3540008f2ad6c","link":"","comment":"<p><a class=\"at\" href=\"#5e7223b198a3540008f2ad6c\">@Anonymous </a> , 是 <code>styles.styl</code> 中的设置（记得在主题配置文件里把对应这个文件的那一行注释去掉哦），应该是很多项设置结合起来的，你可能需要一个一个试试看，具体的值我也忘记了，上面的注释也只是一个大致的备忘记录。</p>\n","rid":"5e7223b198a3540008f2ad6c","objectId":"5e72262598a3540008f2b089","browser":"Safari 13.0.5","os":"Mac OS 10.15.3"}]},{"nick":"小嵩","mail":"d41d8cd98f00b204e9800998ecf8427e","insertedAt":{"__type":"Date","iso":"2020-03-09T09:56:34.732Z"},"link":"","comment":"<p>阅读统计是什么平台</p>\n","objectId":"5e6612d473f4b700096b202d","browser":"Chrome 80.0.3987.122","os":"Windows 7","children":[{"nick":"小嵩","mail":"d41d8cd98f00b204e9800998ecf8427e","insertedAt":{"__type":"Date","iso":"2020-03-09T10:35:50.218Z"},"pid":"5e66131540595e0008b47048","link":"","comment":"<p><a class=\"at\" href=\"#5e66131540595e0008b47048\">@班班 </a> , 嗯，谢谢，你博客写的很好。</p>\n","rid":"5e6612d473f4b700096b202d","objectId":"5e661c0873f4b700096b2685","browser":"Chrome 80.0.3987.122","os":"Windows 7"},{"nick":"班班","mail":"cc763511474fe24ffcc80257fb7cb970","insertedAt":{"__type":"Date","iso":"2020-03-09T09:57:41.545Z"},"pid":"5e6612d473f4b700096b202d","link":"","comment":"<p><a class=\"at\" href=\"#5e6612d473f4b700096b202d\">@小嵩 </a> , LeanCloud，NexT 的配置文件里有的</p>\n","rid":"5e6612d473f4b700096b202d","objectId":"5e66131540595e0008b47048","browser":"Safari 13.0.5","os":"Mac OS 10.15.3"}]},{"nick":"Anonymous","mail":"ad6ede2616b78babc44e4d6f7e8ae747","insertedAt":{"__type":"Date","iso":"2020-03-08T12:24:56.541Z"},"link":"","comment":"<p>谢谢你啊，班班~ </p>\n","objectId":"5e64e41973f4b700096a2479","browser":"Chrome 80.0.3987.132","os":"Windows 10","children":[]},{"nick":"小嵩","mail":"d41d8cd98f00b204e9800998ecf8427e","insertedAt":{"__type":"Date","iso":"2020-03-08T07:03:22.323Z"},"link":"","comment":"<p>你好，这个评论系统是什么呀</p>\n","objectId":"5e6498ba40595e0008b33cf2","browser":"Chrome 80.0.3987.122","os":"Windows 7","children":[{"nick":"小嵩","mail":"d41d8cd98f00b204e9800998ecf8427e","insertedAt":{"__type":"Date","iso":"2020-03-09T09:39:31.788Z"},"pid":"5e64999940595e0008b33db7","link":"","comment":"<p><a class=\"at\" href=\"#5e64999940595e0008b33db7\">@班班 </a> , 好的</p>\n","rid":"5e6498ba40595e0008b33cf2","objectId":"5e660ed640595e0008b46d32","browser":"Chrome 80.0.3987.122","os":"Windows 7"},{"nick":"班班","mail":"cc763511474fe24ffcc80257fb7cb970","insertedAt":{"__type":"Date","iso":"2020-03-08T07:07:05.548Z"},"pid":"5e6498ba40595e0008b33cf2","link":"","comment":"<p><a class=\"at\" href=\"#5e6498ba40595e0008b33cf2\">@小嵩 </a> , 评论区右下角有标注和链接哦，是 Valine</p>\n","rid":"5e6498ba40595e0008b33cf2","objectId":"5e64999940595e0008b33db7","browser":"Safari 13.0.5","os":"Mac OS 10.15.3"}]},{"nick":"leeee.top","mail":"19daa01223d6f593d3e4e875a368163c","insertedAt":{"__type":"Date","iso":"2020-02-24T04:19:52.129Z"},"link":"","comment":"<p>班班，你标题的字体能不能借我抄一下，找了好久没找到，github上的源码没有next的部分</p>\n","objectId":"5e534ee9f94e0f00084527c5","browser":"Chrome 80.0.3987.116","os":"Mac OS 10.15.2","children":[{"nick":"班班","mail":"cc763511474fe24ffcc80257fb7cb970","insertedAt":{"__type":"Date","iso":"2020-02-24T04:23:03.832Z"},"pid":"5e534ee9f94e0f00084527c5","link":"","comment":"<p><a class=\"at\" href=\"#5e534ee9f94e0f00084527c5\">@leeee.top </a> , 标题字体是 Google 字体 Long Cang，源代码 GitHub 上有的哦，可以看这里 <a href=\"https://github.com/lei2rock/blog/blob/master/_config.yml\">https://github.com/lei2rock/blog/blob/master/_config.yml</a></p>\n","rid":"5e534ee9f94e0f00084527c5","objectId":"5e534fa86c073d0009d4265d","browser":"Safari 13.0.5","os":"Mac OS 10.15.3"}]}]}
```

**Comment by lizheming** [comment]
@MHuiG 这是他的接口你看一下数据？https://waline.dlzhang.com/comment?path=/more/&pageSize=6&page=1 我这初步看了下好像没啥问题。

**Comment by lizheming** [comment]
@lei2rock 你这个数据不太对…应该不是 fix 之后转换的数据吧…

**Comment by lei2rock** [comment]
我的 CloudBase 接口是这个啦： https://walinedash-6gnyek4g54f1eaf7-1256060851.ap-shanghai.service.tcloudbase.com

**Comment by lei2rock** [comment]
> @lei2rock 你这个数据不太对…应该不是 fix 之后转换的数据吧…

我再转换一遍试试看

**Comment by lizheming** [comment]
@lei2rock 我看这次数据应该是正常了。

**Comment by lei2rock** [comment]
@lizheming 还是有问题呀

**Comment by lizheming** [comment]
@MHuiG 嗯，我之前是看 Valine 那边用的 insertedAt 就都用的这个字段……

**Comment by MHuiG** [comment]
API文档完善下😄

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/100755298-ffcda180-3426-11eb-9686-5ee748daee79.png)

**Comment by lizheming** [comment]
@MHuiG 好的，字段说明之后补充上 👍

**Comment by lei2rock** [comment]
时间问题解决了（使用新的miniValine后），不过 https://github.com/lizheming/waline/issues/51#issuecomment-736400883 提到的问题还存在，控制台报错依然如此。

**Comment by lizheming** [comment]
看起来好像是接口发布之后返回的数据有问题，我看一下。

**Comment by MHuiG** [comment]
我那边是用JSON.parse解析的

**Comment by MHuiG** [comment]
我这里还有一个createdAt明天再搞了

https://github.com/MiniValine/MiniValine/blob/master/src/utils/fetch/waline/Base.js#L95

**Comment by lizheming** [comment]
@MHuiG 查了下应该是 comment 内容最后有一个 "\n" 前端 JSON.parse 这块挂掉了，我看下是怎么出来的这个东西。

**Comment by lizheming** [comment]
发布评论的问题是服务端使用 CloudBase 返回的数据格式的问题，0.10.2 已修复，可以更新一下看看。MiniValine 这边不需要看了。

**Comment by lizheming** [comment]
@MHuiG 那个 createdAt 也不急，服务端这边是自己生成的 insertedAt 😄 所以不应该这个 issue 的问题了就是。目前 @lei2rock 应该是 MiniValine@5.0.0-alpha.6 和 @waline/vercel@0.10.2 这两个版本应该就都正常了。

**Comment by MHuiG** [comment]
那这样的话那一行应该直接删掉

**Comment by lizheming** [comment]
@MHuiG 嗯，是的，直接去掉就行

**Comment by lei2rock** [comment]
> @MHuiG 那个 createdAt 也不急，服务端这边是自己生成的 insertedAt 😄 所以不影响这个 issue 的问题了就是。目前 @lei2rock 应该是 MiniValine@5.0.0-alpha.6 和 @waline/vercel@0.10.2 这两个版本应该就都正常了。

可是我这边重新部署后还是有问题呀，测试好几次了，有时候还出现无法提交的问题（就是一直加载没有存储没有通知）。云函数日志都显示正常。

**Comment by lei2rock** [comment]
无法提交时候如下，提交成功的时候还是前面提到的那样的情况，整体反应速度比用 LeanCloud 慢多了
![image](https://user-images.githubusercontent.com/19180725/100763758-905caf80-3430-11eb-8af4-ec9053213886.png)

**Comment by lei2rock** [comment]
如果发布表情包还会出现如下错误
![image](https://user-images.githubusercontent.com/19180725/100764667-8c7d5d00-3431-11eb-998c-a25e3a7c708a.png)

**Comment by lei2rock** [comment]
普通的文字评论就会有如下报错
![image](https://user-images.githubusercontent.com/19180725/100764774-ad45b280-3431-11eb-9f8b-ee2657252aea.png)

**Comment by lizheming** [comment]
明天我看看吧，CORS 错误这个又是一个新的问题了好像，我自己这边部署测试都是OK的

**Comment by lei2rock** [comment]
> 明天我看看吧，CORS 错误这个又是一个新的问题了好像，我自己这边部署测试都是OK的

CORS 这个感觉偶尔出现，可能不是大问题（总体感觉响应速度上不如LeanCloud，不知道是网络问题还是其他因素

**Comment by lizheming** [comment]
> > 明天我看看吧，CORS 错误这个又是一个新的问题了好像，我自己这边部署测试都是OK的
> 
> CORS 这个感觉偶尔出现，可能不是大问题（总体感觉响应速度上不如LeanCloud，不知道是网络问题还是其他因素

嗯，没事，我明天自己重新走一遍所有的流程配合  minivaline 重新测试一下

**Comment by eallion** [comment]
> CORS 这个感觉偶尔出现，可能不是大问题（总体感觉响应速度上不如LeanCloud，不知道是网络问题还是其他因素

我看你博客原代码用的是自定义域名：[#L153](https://github.com/lei2rock/blog/blob/3b2dee1e3ae3f385b8814d19f6cf814c97308a1c/_config.yml#L153)， 你试试用云开发默认提供的域名。目前云开发的控制台还很简陋，很多坑。

**Comment by lei2rock** [comment]
> > CORS 这个感觉偶尔出现，可能不是大问题（总体感觉响应速度上不如LeanCloud，不知道是网络问题还是其他因素
> 
> 我看你博客原代码用的是自定义域名：[#L153](https://github.com/lei2rock/blog/blob/3b2dee1e3ae3f385b8814d19f6cf814c97308a1c/_config.yml#L153)， 你试试用云开发默认提供的域名。目前云开发的控制台还很简陋，很多坑。

我前面说的都是用云开发的域名（由于博客的本地测试），我自定义域名是接着 LeanCloud 的数据库（目前用于上线的博客站点）

**Comment by lei2rock** [comment]
@eallion 你博客评论数据为什么加载这么快，我无论是用 LeanCloud 还是云开发都要等一会才会加载出来😂😂

**Comment by eallion** [comment]
> @eallion 你博客评论数据为什么加载这么快，我无论是用 LeanCloud 还是云开发都要等一会才会加载出来😂😂

昨天我测试 MiniValine 发现，获取 IP 的 API 是日本的服务器(？) 然后是 Gravatar 我用是的七牛云的 CDN。

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/100813743-f40bca80-347a-11eb-8853-d3a6119cec26.png)

**Comment by MHuiG** [comment]
这个demo似乎挂掉了

https://minivaline.js.org/waline.html

**Comment by eallion** [comment]
@MHuiG 大概什么时候发 5.0 正式版？

**Comment by MHuiG** [comment]
2202年

**Comment by eallion** [comment]
Sounds good!

**Comment by lizheming** [comment]
目前已定位到问题，MiniValine 发布评论评论框不初始化的原因是因为发布评论数据里面返回的 objectId 异常，MiniValine 这边会根据这个 objectId 取 DOM 导致报错了没有走后续的流程。昨天这块应该是已经修复了的，我待会再看一下。

---

@MHuiG 建议你这块只 try...catch `JSON.parse()` 部分，现在把  `options.success()` 也包裹进去了，实际上回调执行的抛错也会进入 catch 逻辑，可能不太符合直觉？

https://github.com/MiniValine/MiniValine/blob/b3e60efd8ea95a09a27a09cf07491824fa6a79b9/src/utils/plugins/ajax.js#L17-L22

**Comment by lizheming** [comment]
> 目前已定位到问题，MiniValine 发布评论评论框不初始化的原因是因为发布评论数据里面返回的 objectId 异常，MiniValine 这边会根据这个 objectId 取 DOM 导致报错了没有走后续的流程。昨天这块应该是已经修复了的，我待会再看一下。

我确认了一下，确实昨天应该已经修复了这个问题。腾讯云开发这边没生效可能是依赖没更新的问题，进入云函数界面点击 <kbd>保存并安装依赖</kbd> 重新部署一下试试呢？@lei2rock

@MHuiG 另外接口目前返回的状态码不太标准，之后会把所有的接口失败全部返回 500 状态码，你那边可以针对非 200 的状态码做一下错误的兼容处理。（比如发布评论过快，重复内容之类的）

**Comment by MHuiG** [comment]
https://waline.vercel.app/

demo挂掉了

**Comment by lizheming** [comment]
@MHuiG 好了，我这个部署的版本好像有点老，更新了一下。 错误码的修改 `@waline/vercel@0.11.0` 已发布，你那边可以适配了。

**Comment by lei2rock** [comment]
我部署了最新到 waline+MiniValine 之后基本上解决了之前提到的各种问题，但是遇到一个新问题：后台管理无法登录，也无法重新注册账号（不论是 LeanCloud 还是 CloudBase 都是如此）

**Comment by lizheming** [comment]
@lei2rock 你好，这个 issue 上附带的问题太多了，如果原本的问题都已解决的话，我这边就先关闭这个 issue 了。
关于你最新提的这个问题，你先隐私模式下试试行不行。另外你那边帮忙把最近的这个问题新开一个 issue 吧，我们可以在新 issue 上沟通这个问题。
