### ISSUE TITLE
服务端是否有网站白名单设置

### ISSUE THREAD

**Issue by lei2rock** [lizheming/waline#52]
serverURL 暴露出来的话似乎可以被任何填写该链接的网站获取评论数据，是否有白名单功能限制使用的网站？

**Comment by lizheming** [comment]
嗯，我晚点加一下

**Comment by lizheming** [comment]
https://waline.js.org/server/basic.html#securedomains 增加了 `secureDomains` 配置，具体配置写法见文档。

如果是 Vercel 部署的话把仓库的 package.json 文件的 `@waline/vercel` 版本改成 0.10.0 即可。

**Comment by lei2rock** [comment]
自己服务器的docker部署或者CloudBase怎么配置呢？环境变量可以直接填写，项目代码配置并不知道怎么搞😂

**Comment by lizheming** [comment]
Cloudbase 在云函数界面里可以修改代码。Docker 部署的话要做一下文件映射

```
docker run -v config.js:/opt/waline/config.js lizheming/waline
```

然后 `config.js` 里面这么写就可以了 

```
//config.js
module.exports = {
  secureDomains: 'waline.js.org'
};
```

环境变量的支持我之后加一下吧，不过环境变量的配置就要简单了，只能配字符串了。

**Comment by lei2rock** [comment]
I see. 不过我觉得支持环境变量设置会方便一点～

**Comment by lizheming** [comment]
简单配置适合放环境变量，复杂配置还是放代码比较方便一点，这块主要是需要支持多安全域名和正则域名的形式，所以放配置里了。环境变量我也加一下。

**Comment by lizheming** [comment]
https://waline.js.org/server/basic.html#%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE 环境变量加上了 `SECURE_DOMAINS`

**Comment by OrageKK** [comment]
请问这个功能的意义是否是在我配置域名的网站发起请求可以，从其他地方发起请求不可以，比如有人用apifox，postman等工具一直调接口刷恶意评论，能否防止。我试了一下，好像不管用

**Comment by lizheming** [comment]
@OrageKK 这个没有哈，恶意评论可以通过添加验证码解决。

**Comment by OrageKK** [comment]
> @OrageKK 这个没有哈，恶意评论可以通过添加验证码解决。
> 
> @OrageKK This is not a problem. Malicious comments can be solved by adding a verification code.

那问一下这个安全域名有什么作用呢，任何来源都可以调用api，leancloud也有一个安全域名配置，解释为：设置 Web 安全域名后，仅可在该域名下通过 JavaScript SDK 调用服务器资源。不知是否可以屏蔽域名之外的API调用

**Comment by lizheming** [comment]
@OrageKK 可以理解为这个安全域名和 LeanCloud 的安全域名是一个概念，主要是防止其他网站直接使用自己的 serverURL 的。

**Comment by axiaoxin** [comment]
请问一下：

我把waline私有部署在 waline.my-domain.com 上，服务端在环境变量中设置了一个不存在的域名 SECURE_DOMAINS="not-exists.com" 然后在a.com上使用waline.my-domain.com 还是能正常展示和提交评论，这是正常的吗，还是我用法不对？
