### ISSUE TITLE
评论中链接的打开方式

### ISSUE THREAD

**Issue by eallion** [lizheming/waline#53]
目前评论中的链接打开方式为本窗口打开，这不太符合亚洲人的使用习惯，希望可以在上游就设置为在新窗口打开，或者增加开关。

**Comment by lizheming** [comment]
好的，之后加一下，我看看是加前端合适还是加数据转换合适。

**Comment by lizheming** [comment]
看了下目前在前端加负担比较轻一点，`@waline/client` 更新到了 0.5.2 了，可以试试。

**Comment by eallion** [comment]
@lizheming 建议内链在本窗口打开，还有@回复的链接不处理，或链接到定位锚点。

**Comment by lizheming** [comment]
可以，我处理一下。

**Comment by lizheming** [comment]
`@waline/client@0.5.3` 增加了 @ 回复和内链的过滤处理 https://github.com/lizheming/waline/commit/13c88ed8cf5f74fa1c827b815f7d39761a450562

不过需要注意的是是否是内链的判断规则是是否是相对路径 URL，带有本站 Host 的绝对 URL 还是会被认为是外链，这里稍微注意下。
