### ISSUE TITLE
后台管理界面评论链接404问题

### ISSUE THREAD

**Issue by YinAoXiong** [lizheming/waline#54]
现状：目前后天评论链接显示是以相对路径的方式进行显示
问题：而一般来说waline后端和博客没有部署在统一域名下，所以点击查看跳转后会出现404错误
意见：可以增加一个获取SITE_URL的api，在后台显示SITE_URL对应文章的绝对路径；后端能否像client一样增加一个serverURL的配置进行以便有需要的人独立部署。

**Comment by lizheming** [comment]
可以的，现在就有 `SITE_URL` 的配置，只是之前偷懒没注到前端所以前端这也偷懒没加这块。之后补充一下。

**Comment by lizheming** [comment]
目前增加了 `SITE_URL` 字段的拼接解决该问题。

- 如果是 Docker 部署的更新下镜像即可。
- 如果是 CloudBase 部署的进入后台保存并更新依赖即可。
- 如果是 Vercel 的项目的话可以按照
 https://github.com/lizheming/waline/blob/master/example/vercel.json 修改下 `vercel.json` 文件，同时把 `package.json` 中的 `@waline/vercel` 更新到 `0.11.0` 的版本即可。

不过该修复隐藏的问题是现在是如果用户设置的 `path` 不是 `location.pathname` 的话可能拼接就有问题了，目前暂时先不考虑该问题。
