### ISSUE TITLE
CloudBase 感觉问题很大，又出现了提交评论加载半天的情况

### ISSUE THREAD

**Issue by lei2rock** [lizheming/waline#57]
CloudBase 感觉问题很大，总是各种各样问题，本来还打算整体迁移过去的，现在看来还不如 docker 搭建 Waline 然后数据从LeanCloud 取

情况一：能提交评论，有通知，但是加载图标一直显示加载
![Xnip2020-12-04_00-12-57](https://user-images.githubusercontent.com/19180725/101056219-b798b580-35c5-11eb-99c3-44a2d784f090.jpg)

情况二：无法提交评论
![Xnip2020-12-04_00-13-27](https://user-images.githubusercontent.com/19180725/101056225-b8c9e280-35c5-11eb-8331-25ac80dae84f.jpg)

情况三：无法加载既有评论
![image](https://user-images.githubusercontent.com/19180725/101056269-c41d0e00-35c5-11eb-9450-51c8ab1378d8.png)

**Comment by lizheming** [comment]
1. 是发布了重复评论，这个需要 MiniValine 那边根据非 200 状态码适配一下
2. 这个是 cloudbase 的报错，具体我之后再查一下
3. 这个是 MiniValine 的报错，我之前有时候也能刷出来，再刷新下又好了，还挺奇怪的。

目前如果想稳定使用的话比较建议 Vercel 配合 Leancloud 食用方案，其他的兼容环境方案上线比较匆忙，难免会有一些问题。

**Comment by lei2rock** [comment]
嗯，本来打算全面抛弃 LeanCloud，目前看来还是暂时自己服务器 Docker 部署的后端 + LeanCloud 的方案吧，等各种兼容适配了再换

**Comment by eallion** [comment]
暂时测试没有问题。

**Comment by MHuiG** [comment]
https://waline.vercel.app/

这个demo不能提交评论

**Comment by MHuiG** [comment]
> 嗯，本来打算全面抛弃 LeanCloud，目前看来还是暂时自己服务器 Docker 部署的后端 + LeanCloud 的方案吧，等各种兼容适配了再换

刚刚看了一下，腾讯云免费版的限制是按月累计，而leancloud是按天累计（不能刷写入评论的限制，还可以刷读评论的限制嘛 

安全域名因为开发需要并没有过滤localhost，攻击者似乎可以直接在localhost下搞

**Comment by lizheming** [comment]
> > 嗯，本来打算全面抛弃 LeanCloud，目前看来还是暂时自己服务器 Docker 部署的后端 + LeanCloud 的方案吧，等各种兼容适配了再换
> 
> 刚刚看了一下，腾讯云免费版的限制是按月累计，而leancloud是按天累计（不能刷写入评论的限制，还可以刷读评论的限制嘛
> 
> 安全域名因为开发需要并没有过滤localhost，攻击者似乎可以直接在localhost下搞

你可以试一下，除去我说的 Docker 独立部署的情况使用端口访问的问题，其它的情况是不行的。

**Comment by MHuiG** [comment]
> > > 嗯，本来打算全面抛弃 LeanCloud，目前看来还是暂时自己服务器 Docker 部署的后端 + LeanCloud 的方案吧，等各种兼容适配了再换
> > 
> > 
> > 刚刚看了一下，腾讯云免费版的限制是按月累计，而leancloud是按天累计（不能刷写入评论的限制，还可以刷读评论的限制嘛
> > 安全域名因为开发需要并没有过滤localhost，攻击者似乎可以直接在localhost下搞
> 
> 你可以试一下，除去我说的 Docker 独立部署的情况使用端口访问的问题，其它的情况是不行的。

举个例子

cloudbase 免费版 下载操作次数限制150万/月
这个客户端Demo https://waline.vercel.app/ 在localhost下是可以正常访问的，然后就可以搞事情了呀

**Comment by lizheming** [comment]
@MHuiG 我大概明白你说的意思了，本地 localhost 启一个服务，然后 serverURL 用其它人的，这种的确目前没有办法。不过我们增加 SECURE_DOMAIN 的主要原因是为了防止接口在其它网站上滥用，所以这种情况还好。
这个功能是无法防止搞事情的，包括刷 API 接口和发布评论，毕竟这些直接刷博主的网站就可以了。主要还是之前用户提出的防止 A 网站的评论数据在 B 网站出现被其它用户看到吧。

**Comment by MHuiG** [comment]
安全起见，把这一段删掉

**Comment by lizheming** [comment]
@MHuiG 那个删除与否没什么意义，如果考虑本地的话甚至可以把博客域名指向本地处理，这个没办法的。

**Comment by MHuiG** [comment]
我是说删掉这一段issue

**Comment by lizheming** [comment]
@MHuiG 哈哈，好的，那我把相关讨论删除一下。

**Comment by lizheming** [comment]
@MHuiG demo 不能评论是因为之前有人跑到 waline 官方上发垃圾评论，我就索性设置了下 `preSave()` 禁止评论了。这块由于设置了太久，导致我自己都忘记了今天还查了半天，目前已恢复了 😓。

**Comment by lei2rock** [comment]
反馈一下：改用 Waline 最新支持 hexo next 主题的插件后似乎使用体验改善很多，用 CloudBase 也很顺畅了

**Comment by lizheming** [comment]
@lei2rock 关于反馈的问题2无法提交评论，提示的是 `timeout 5 seconds` 的问题，昨天帮另外一位网友排查，可能是以为邮件通知耗时比较长导致的超时。可以在后台把超时时间设置大一点再试试。

**Comment by MHuiG** [comment]
> demo 不能评论是因为之前有人跑到 waline 官方上发垃圾评论，我就索性设置了下 `preSave()` 禁止评论了。这块由于设置了太久，导致我自己都忘记了今天还查了半天，目前已恢复了 😓。

这边一三问题搞定了

5.0.0-alpha.17

**Comment by lizheming** [comment]
@MHuiG 收到，非常感谢~ @lei2rock 你要有时间的话可以用回 MiniValine 再试试，如果没时间的话我就当已解决暂时关闭这个 issue，之后如果还有问题我们可以开新 issue 再讨论。非常感谢二位~

**Comment by MHuiG** [comment]
你的官网Demo又挂掉了https://minivaline.js.org/waline.html

似乎 waline cli 没有异常提示

有人遇到一个跨域问题
https://mcseekeri.top/comment/

**Comment by lizheming** [comment]
@MHuiG 官网的 DEMO 因为 Vercel 账户超额暂时使用不了。提示跨域问题一般是接口有错误，没有走到设置跨域头的逻辑里。可以让用户上 Vercel 后台看一下请求返回的错误日志。

**Comment by lizheming** [comment]
@MHuiG 跨域的问题你让这位用户把 serverURLs 最后的那个 / 去掉试一下 `https://mccomments.now.sh` 我这看好像是因为双斜线的问题，去掉了似乎正常了。

**Comment by MHuiG** [comment]
> @MHuiG 跨域的问题你让这位用户把 serverURLs 最后的那个 / 去掉试一下 `https://mccomments.now.sh` 我这看好像是因为双斜线的问题，去掉了似乎正常了。

@MCSeekeri

**Comment by MCSeekeri** [comment]
去掉之后正常了（
不过似乎发布评论之后刷新就没了,但访问Waline的后台是可以看到已经正常发布的...
我估计是我自己魔改旧版Volantis的问题,回头升级到4.2.0再试试

**Comment by lizheming** [comment]
@MCSeekeri 这个不是你的问题，前几天也有其他用户反馈，默认不设置 path 的情况下，读取评论列表时候接口传的 path 是undefined。不过发布评论的时候是正常的。 @MHuiG 有空的话帮忙看看这个问题吧，谢谢。

**Comment by MHuiG** [comment]
@MCSeekeri 先升级到4.2.0

**Comment by MHuiG** [comment]
> @MCSeekeri 这个不是你的问题，前几天也有其他用户反馈，默认不设置 path 的情况下，读取评论列表时候接口传的 path 是undefined，导致读取评论不正确，不过发布评论的时候是正常的。 @MHuiG 有空的话帮忙看看这个问题吧，谢谢。

那里的其他用户

**Comment by lizheming** [comment]
> > @MCSeekeri 这个不是你的问题，前几天也有其他用户反馈，默认不设置 path 的情况下，读取评论列表时候接口传的 path 是undefined，导致读取评论不正确，不过发布评论的时候是正常的。 @MHuiG 有空的话帮忙看看这个问题吧，谢谢。
> 
> 哪里的其他用户

@QingxuMo 之前在 waline 的 tg 群里反馈的，我自己用了下确实能复现，手动指定 path 正常。

**Comment by MHuiG** [comment]
那就先手动指定吧

**Comment by MHuiG** [comment]
@MCSeekeri @QingxuMo 5.0.0-alpha.19 解决path问题

![image](https://user-images.githubusercontent.com/38281581/102042139-0e935b80-3e0c-11eb-919e-0b4296c47a0a.png)

**Comment by MHuiG** [comment]
@MCSeekeri 顺便提一句表情包格式改了

https://github.com/MiniValine/MiniValine/releases/tag/v5.0.0-alpha.2

**Comment by MCSeekeri** [comment]
好...感谢提醒（
我等我用的表情包生成脚本更新了就换（
（因为我技术水平弱鸡不大会写json
