### ISSUE TITLE
增加 MathJax 的解析支持

### ISSUE THREAD

**Issue by lizheming** [lizheming/waline#58]

**Comment by mrj1018** [comment]
我有一个站很需要数学公式解析，请问您还有计划做这方面的支持吗？谢谢！

**Comment by lizheming** [comment]
已经支持了的，`$$x^2$$` 你试试

**Comment by mrj1018** [comment]
噢，我这边的环境确实主要是 Chrome 系的，所以效果不是太好。请问能不能提供用 KaTeX 渲染成 HTML 的选项呢？我之前有个 hexo 站用的是 Valine，用 KaTeX 渲染成 HTML，Chrome 和 Firefox 都能比较完美地显示。

![效果](https://user-images.githubusercontent.com/16172713/103061303-e531b700-45e5-11eb-9e48-67c6b3249771.png)

![结构](https://user-images.githubusercontent.com/16172713/103061381-288c2580-45e6-11eb-94c2-3cfb624d6e0c.png)

**Comment by lizheming** [comment]
我这边试了下 HTML 渲染不太行才用的 MathML 的，可能和 Waline 是在服务端渲染数学公式有关系。目前先只能这样了，等之后看看是否有更好的解决方案吧。

**Comment by mrj1018** [comment]
好的，谢谢！
