### ISSUE TITLE
文档里写了支持 PostgreSQL，但实际尚未实现？

### ISSUE THREAD

**Issue by XiongLiding** [lizheming/waline#59]
建表语句链接的是 MySQL 的，Storage 目录里也没有 postgresql.js

**Comment by lizheming** [comment]
就是复用的 MySQL 的，服务端使用的 ThinkJS 框架在 ORM 层会自动适配 MySQL, SQLite 和 PostgreSQL。（不过 PG 这块可能会有些小差别，可以试试，有问题欢迎反馈

**Comment by XiongLiding** [comment]
实际执行创建用户的功能，卡在这一行

https://github.com/lizheming/waline/blob/93e36929d718f249db97fbc4ada73f87248de7aa/packages/server/src/service/storage/mysql.js#L43

在 await 这里卡住了，这个 Promise 既没 resolve 也没 reject。

![image](https://user-images.githubusercontent.com/679318/101450061-de0f7580-3964-11eb-859a-528398aa64ed.png)

数据库应该能连上，waline 日志里的输出的连接串用 psql 直接连是能进的。

vscode 调试看到的查询语句手工放到数据库里运行也是正确的。

可能是哪里出问题了？

**Comment by lizheming** [comment]
收到，我之后调试一下试试，有结论 issue 回复

**Comment by lizheming** [comment]
你好，经确认确实有一些未兼容 pg 的地方。主要的修改如下：

1. 增加了 pg 单独的数据表创建脚本 `waline.pgsql`
2. 增加了 pg 单独的存储适配层 `storage/postgresql.js`
3. 更新了底层的 pg 连接依赖，解决本 issue 反馈的配置信息无问题但是连接不上的问题

- 如果是 Vercel 部署的版本将 `package.json` 中 `@waline/vercel` 依赖版本修改成 `0.13.2` 之后等待部署即可。
- 如果是 CloudBase 云开发部署的话直接在后台选择 <kbd>更新依赖并部署</kbd> 即可。
- 如果是 Docker 独立部署的重新更新下镜像即可。

已经重新跑了一遍流程确认 pg 这块没有问题了，欢迎有问题再反馈。

**Comment by XiongLiding** [comment]
测试过新的 Docker 镜像已经可以了

**Comment by lizheming** [comment]
收到，非常感谢使用，后续有任何问题可以随时开 issue 跟进。
