### ISSUE TITLE
网址中有中文字符时，计数器读取异常

### ISSUE THREAD

**Issue by XiongLiding** [lizheming/waline#63]
数据库里存的是 encodeURIComponent 之后的值
![image](https://user-images.githubusercontent.com/679318/101752164-21f0af00-3b0c-11eb-97a7-e150ee643040.png)
id=2 那个是我测试时改成中文的，改完后就能正常显示数据，但新数据还是会新建一个 id=5 那条去。

查询时查的是 decodeURIComponent 之后的值
![image](https://user-images.githubusercontent.com/679318/101752356-63815a00-3b0c-11eb-9e28-061d533db588.png)

**Comment by lizheming** [comment]
那可能是读取这块有点问题，是否有页面给我我这边看一下？

**Comment by XiongLiding** [comment]
路径有中文的阅读次数是0
https://bnlt.org/2020/%E8%AF%BB%E3%80%8A%E7%A8%8B%E5%BA%8F%E5%91%98%E4%BF%AE%E7%82%BC%E4%B9%8B%E9%81%93%E3%80%8B/

没有中文的就正常
https://bnlt.org/2018/Simple-nginScript/

**Comment by lizheming** [comment]
查了下原因是更新统计的时候使用的是编码后的 URL，而读取的时候会做解编码的相关操作导致的，目前已针对更新操作也做了解码操作。

注意，该修改会对这种场景下的评论数据展示也会有影响，老的数据因为 URL 路径不匹配可能会无法展示。如需要老数据的可能需要统一对老数据进行下 URL 解码操作。
