### ISSUE TITLE
从 valine 迁移到自建数据库的函数

### ISSUE THREAD

**Issue by XiongLiding** [lizheming/waline#64]
看到文档里有个从 valine 迁移到 cloudbase 的转换脚本：
https://waline.js.org/migration.html#%E8%BF%81%E7%A7%BB%E8%87%B3-cloudbase

我自己写了个转换到 CSV 格式的函数，可以方便导入到自建数据库：
https://gist.github.com/XiongLiding/fc70b644c54d0c2bc1a6ed788469a93a

**Comment by lizheming** [comment]
赞一个，SQL 类的应该都可以用这个，我之后加到文档中，非常感谢！
