### ISSUE TITLE
后台无法删除评论（CloudBase 部署）

### ISSUE THREAD

**Issue by lei2rock** [lizheming/waline#65]
会有两种情况（云函数执行没有报错）：

- 一种是可以点击删除，然后评论消失，但是刷新后台评论还在；
- 另一种是点击删除没有反应，控制台报错如下

![Xnip2020-12-15_08-27-28](https://user-images.githubusercontent.com/19180725/102152219-8070b100-3eaf-11eb-81fe-4f924439ac38.jpg)

**Comment by lizheming** [comment]
可以上 CloudBase 日志里看看错误日志，看下具体的错误是什么

**Comment by lei2rock** [comment]
![IMG_0042](https://user-images.githubusercontent.com/19180725/102156435-861ec480-3eb8-11eb-88c9-def48625fd1f.jpeg)
![IMG_0043](https://user-images.githubusercontent.com/19180725/102156440-88811e80-3eb8-11eb-9c49-0d7733908f6b.jpeg)

**Comment by lizheming** [comment]
左上角可以做筛选，选择调用失败的看看，这些都是调用成功的。

**Comment by lei2rock** [comment]
调用失败的都不是今天的，是很早以前的。今天都是成功的

**Comment by lizheming** [comment]
那你捞一下最终报错的那条日志吧，你截图的这些好像都不太明确

**Comment by lei2rock** [comment]
这个都是很古老的报错日志了，应该是之前讨论的issue导致的报错
![IMG_0044](https://user-images.githubusercontent.com/19180725/102160345-3b08af80-3ec0-11eb-8122-be2120f07165.jpeg)

**Comment by lei2rock** [comment]
又重新部署了一下，现在变成后台无法读取评论了。控制台和云开发的记录如下
![Xnip2020-12-16_15-08-12](https://user-images.githubusercontent.com/19180725/102316447-e6912d00-3fb0-11eb-832b-ce260695eca9.jpg)
![Xnip2020-12-16_15-09-44](https://user-images.githubusercontent.com/19180725/102316454-e8f38700-3fb0-11eb-84aa-16cdd7a9f0f7.jpg)

**Comment by lei2rock** [comment]
![Xnip2020-12-16_15-13-01](https://user-images.githubusercontent.com/19180725/102316667-4e477800-3fb1-11eb-8d51-3249e6f66bc3.jpg)
![Xnip2020-12-16_15-13-19](https://user-images.githubusercontent.com/19180725/102316680-53a4c280-3fb1-11eb-88df-967da0451d02.jpg)
![Xnip2020-12-16_15-13-37](https://user-images.githubusercontent.com/19180725/102316686-54d5ef80-3fb1-11eb-92d7-5be9d3735236.jpg)


![Xnip2020-12-16_15-13-10](https://user-images.githubusercontent.com/19180725/102316678-51daff00-3fb1-11eb-9ba5-e1d717f68851.jpg)

**Comment by lizheming** [comment]
读取的问题可以重新更新下依赖，是昨天修改的一点 BUG，已发布 @waline/vercel@0.13.5 修复了。

**Comment by lei2rock** [comment]
还是不行，报错
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/19180725/102318264-0413c600-3fb4-11eb-86ed-308826a4ffda.png">

**Comment by lizheming** [comment]
你这个是 token 有问题，隐私模式下看看

**Comment by lei2rock** [comment]
隐私模式下，控制台报错一样，还是不能加载评论
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/19180725/102319180-6caf7280-3fb5-11eb-9720-8c07dbc693f5.png">

**Comment by lizheming** [comment]
DATABASE_REQUEST_FAILED 这个和之前的报错是一样的，可能依赖没更新上，也可能是其它问题，需要更多的错误信息

**Comment by lei2rock** [comment]
能找到的错误信息就这些了😂😂

**Comment by lizheming** [comment]
那就不太好查了。不行的话就换 Vercel 部署试试？

**Comment by lei2rock** [comment]
腾讯云云开发直接无法重新部署应用了，准备去提工单
<img width="538" alt="image" src="https://user-images.githubusercontent.com/19180725/102321441-a46be980-3fb8-11eb-8edb-e100c845f529.png">

**Comment by lei2rock** [comment]
> 那就不太好查了。不行的话就换 Vercel 部署试试？

不想用Vercel，还不如自己docker部署，然后连接到云开发的数据库

**Comment by lizheming** [comment]
嗯，你发工单问问吧，有进度 issue 跟进。ps. Vercel 也可以连云开发的数据库的。

**Comment by lei2rock** [comment]
突然有可以部署了，日志还是差不多内容。实在不行自己部署docker算了，反正博客也在服务器上，放一起比较好管理。
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/19180725/102322822-a2a32580-3fba-11eb-8b27-e83b59a3e886.png">
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/19180725/102323049-f31a8300-3fba-11eb-9437-d7821144d08c.png">
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/19180725/102323073-fada2780-3fba-11eb-825a-12f8db91d6a4.png">

**Comment by lei2rock** [comment]
自己docker部署，然后连接到云开发的数据库，后台可以访问评论。但是无法删除评论的问题依然存在，docker日志没有产生错误信息。啊，好麻烦，感觉要探索一下docker连接mysql数据库管理评论了😂😂😂

**Comment by lizheming** [comment]
有时间你就折腾下吧，没时间就先忽略这个问题，反正自己进数据库里也是能删除的。

**Comment by lei2rock** [comment]
> 有时间你就折腾下吧，没时间就先忽略这个问题，之后我再自己试试，反正自己进数据库里也是能删除的。

是的，反正就先这样吧。
