### ISSUE TITLE
status 字段的兼容问题

### ISSUE THREAD

**Issue by lizheming** [lizheming/waline#67]
需要兼容 Valine 老数据不存在 status 字段的场景，目前仅判断了 status=approved 的数据 https://github.com/lizheming/waline/discussions/66

**Comment by eallion** [comment]
好像不止这一个坑，我忘记我当时处理了哪些了。

**Comment by lizheming** [comment]
@eallion 那你可以帮忙汇总下，我一块处理下

**Comment by eallion** [comment]
但是的真的忘记了。好像有 UA 字段问题，有 邮箱 字段问题（disqus导出的评论没有邮箱），有时间格式问题，有 URL path 问题。
