### ISSUE TITLE
请问云开发如何配置环境变量

### ISSUE THREAD

**Issue by CCKNBC** [lizheming/waline#69]
我是小白，按照js格式在app.js写了相关但貌似没起作用，想问邮件通知等变量如何配置

**Comment by eallion** [comment]
方法一：
1. 点击 [`我的应用`](https://console.cloud.tencent.com/tcb/apps/index)

![1](https://user-images.githubusercontent.com/1698841/102187107-889c1100-3eee-11eb-9fd9-de1f26dde3ac.png)

2. 找到 Waline 应用，点`管理`

![2](https://user-images.githubusercontent.com/1698841/102187189-a0739500-3eee-11eb-8273-1dc7083cb5af.png)

3. 点`编辑`

![3](https://user-images.githubusercontent.com/1698841/102187245-b1bca180-3eee-11eb-9f2c-4bd58d67ba39.png)

4. 新增环境变量
    保存并部署 （重新部署）

![4](https://user-images.githubusercontent.com/1698841/102187306-ca2cbc00-3eee-11eb-9783-b3e88b033589.png)

**Comment by eallion** [comment]
方法二：
1. 点`云函数`进入 Waline

![11](https://user-images.githubusercontent.com/1698841/102187853-82f2fb00-3eef-11eb-9c23-992c4234f9e3.png)

2. 点`编辑`

![22](https://user-images.githubusercontent.com/1698841/102187891-8dad9000-3eef-11eb-8dcb-082df048e7a9.png)

3. 新增环境变量 然后 保存

![33](https://user-images.githubusercontent.com/1698841/102187960-a7e76e00-3eef-11eb-96b8-d54b0cc7a2b3.png)

4. 点击`函数代码`，`保存并安装依赖`

![44](https://user-images.githubusercontent.com/1698841/102188007-bc2b6b00-3eef-11eb-9d6b-032da17fb589.png)

**Comment by CCKNBC** [comment]
谢谢，还想问一下这个以后更新的话是会同步仓库自动升级还是我需要手动复制代码更新

**Comment by lizheming** [comment]
@CCKNBC 如果是 Vercel 部署的话需要更新 package.json 里的那个版本号，如果是 CloudBase 部署的话就是上面回复的最后一张图那块选择 <kbd>保存并安装依赖</kbd> 就可以了。
