### ISSUE TITLE
希望表情功能可以点击后再加载表情图片

### ISSUE THREAD

**Issue by eallion** [lizheming/waline#70]
![Snipaste_2020-12-16_14-05-41](https://user-images.githubusercontent.com/1698841/102311795-74b4e580-3fa8-11eb-8e16-6ae5d89d62f0.png)

**Comment by eallion** [comment]
评论里的`vcontent`里的 `img` 可以添加 `loading="lazy"`属性

**Comment by MHuiG** [comment]
@eallion 这个我推荐 https://github.com/aFarkas/lazysizes

**Comment by MHuiG** [comment]
@eallion 参考https://github.com/xCss/Valine/issues/261
