### ISSUE TITLE
建议添加 Jsdelivr 的 CDN 支持

### ISSUE THREAD

**Issue by dyxang** [lizheming/waline#73]
理由：它在国内有网宿作为合作，国内访问应该体验更好

**Comment by lizheming** [comment]
嗯，这个其实自己改一下地址就行 https://cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js 其实我自己平常用也是用的 jsdelivr 的 😸

**Comment by dyxang** [comment]
> 嗯，这个其实自己改一下地址就行 https://cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js 其实我自己平常用也是用的 jsdelivr 的 😸

看文档我还以为没有😅

**Comment by lizheming** [comment]
嗯，jsdelivr 的地址很棒，支持 Github 和 npm 文件的 CDN 镜像，只要这两个地方能访问到的，jsdelivr 就支持，不需要特别做操作。

**Comment by eallion** [comment]
文档中不知道有没有明说，但我也是一直就是用的 jsDelivr 。

**Comment by lizheming** [comment]
@eallion 文档是参考 valine 的文档改的，所以应该都是用的 unpkg 的地址，确实可以改一下。
