### ISSUE TITLE
前端跨域问题及其他

### ISSUE THREAD

**Issue by dyxang** [lizheming/waline#74]
安装好以后评论无法实时显示，只能刷新页面看，于是查看了控制台。
```ps
Access to fetch at 'https://example.vercel.app/comment' from origin 'https://example.com' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Waline.min.js:40 POST https://example.vercel.app/comment net::ERR_FAILED
```
请问是正常的吗？

**Comment by lizheming** [comment]
你的这个 serverURL 配置有问题吧？https://example.vercel.app 这个 URL 打开 404 额

**Comment by dyxang** [comment]
> 你的这个 serverURL 配置有问题吧？https://example.vercel.app 这个 URL 打开 404 额

啊我只是举个例子，具体的url怕隐私泄露了

**Comment by lizheming** [comment]
这个没有必要的，你要放博客上就会被用户访问的。报跨域问题一般是接口报错了没有走到设置跨域的逻辑，你可以发一下地址我具体看一下是什么原因报错了。

**Comment by dyxang** [comment]
> 这个没有必要的，你要放博客上就会被用户访问的。报跨域问题一般是接口报错了没有走到设置跨域的逻辑，你可以发一下地址我具体看一下是什么原因报错了。
https://talk-pi.vercel.app

**Comment by dyxang** [comment]
另外我还想再问一个问题，文档貌似没有提到的：

- 迁移成功后是否能取消 leancloud 的 valine- admin 云引擎部署？
- 是否能在 Vercel 的 Settings - Environment Variables 中自定义邮件通知模板？

**Comment by lizheming** [comment]
@dyxang 我看了下评论发布似乎没有问题，有博客的地址么可以发一下看看，还有就是如果 serverURL 后面配了 `/` 的话可以去了试一下。
关于你问的两个问题，回复如下：
1. 可以取消，我们不依赖 valine-admin 的，如果同时部署的话可能会造成通知邮件重复发送的问题
2. 可以，`MAIL_TEMPLATE` 是用来定义通知模板的。不过我觉得那么长的东西放在环境变量里写实在是太不人性化了，所以就暂时没在文档中公布，想着是不是有更好的方案来着。

**Comment by dyxang** [comment]
> @dyxang 我看了下评论发布似乎没有问题，有博客的地址么可以发一下看看，还有就是如果 serverURL 后面配了 `/` 的话可以去了试一下。
> 关于你问的两个问题，回复如下：
> 
> 1. 可以取消，我们不依赖 valine-admin 的，如果同时部署的话可能会造成通知邮件重复发送的问题
> 2. 可以，`MAIL_TEMPLATE` 是用来定义通知模板的。不过我觉得那么长的东西放在环境变量里写实在是太不人性化了，所以就暂时没在文档中公布，想着是不是有更好的方案来着。

博客地址：https://1inn.now.sh
具体表现为我按了回复按钮后按钮就不能再按了，同时我的回复也没刷新出来

**Comment by lizheming** [comment]
@dyxang 能进到 talk-pi.vercel.app 的 Vercel 后台看下访问日志里是否有什么错误信息么？

**Comment by dyxang** [comment]
> @dyxang 能进到 talk-pi.vercel.app 的 Vercel 后台看下访问日志里是否有什么错误信息么？

是 Functions 下的 log 么？
```ps
[POST] /comment
12:44:48:64
2020-12-17T04:44:48.786Z	e403197c-b6f3-487b-bf48-ddab87b43063	WARN	marked(): sanitize and sanitizer parameters are deprecated since version 0.7.0, should not be used and will be removed in the future. Read more here: https://marked.js.org/#/USING_ADVANCED.md#options
2020-12-17T04:44:58.781Z e403197c-b6f3-487b-bf48-ddab87b43063 Task timed out after 10.01 seconds
```

**Comment by lizheming** [comment]
啊，这应该是超时了...你是用的 LeanCloud 国内版么？

**Comment by dyxang** [comment]
> 啊，这应该是超时了...你是用的 LeanCloud 国内版么？

国际版

**Comment by lizheming** [comment]
是否有配邮件通知？邮件通知相关的可以去掉再试一下，有可能邮件通知服务配置错误也会导致超时出现。

**Comment by dyxang** [comment]
> 是否有配邮件通知？邮件通知相关的可以去掉再试一下，有可能邮件通知服务配置错误也会导致超时出现。

删了，的确是会刷新了（但是是全局刷新），而且这次评论是否成功都是随机的了……

Vercel log 无错误。`Failed Requests: None`，控制台依旧
```
Waline.min.js:1 marked(): sanitize and sanitizer parameters are deprecated since version 0.7.0, should not be used and will be removed in the future. Read more here: https://marked.js.org/#/USING_ADVANCED.md#options
```

**Comment by lizheming** [comment]
1. 全局刷新是目前客户端实现就是如此，之后会优化成局部刷新。如果你比较介意这点可以更换使用 MiniValine 客户端
2. 评论成功随机，这是因为目前有一个 IP 发送评论的频率限制，默认是 60 秒，你可以通过 `IPQPS` 变量进行修改

目前来看可能就是邮件通知服务这块连接有问题，具体你可以确认下配置这块是否有问题。

**Comment by dyxang** [comment]
> 1. 全局刷新是目前客户端实现就是如此，之后会优化成局部刷新。如果你比较介意这点可以更换使用 MiniValine 客户端
> 2. 评论成功随机，这是因为目前有一个 IP 发送评论的频率限制，默认是 60 秒，你可以通过 `IPQPS` 变量进行修改
> 
> 目前来看可能就是邮件通知服务这块连接有问题，具体你可以确认下配置这块是否有问题。

我照着 Leancloud 上的邮件通知那块的变量移过来的，结果回到一开始的出错了
![](https://i.loli.net/2020/12/17/xmjY5ZHsgzLkI3J.jpg)

**Comment by lizheming** [comment]
那就是邮件通知这块有问题了，有可能是 Vercel 和你的邮箱商不通，有可能是配置有问题，这个我这边具体也不太好排查，可能还需要你自己那边多试一下了。

**Comment by lizheming** [comment]
才发现原来你截了配置图了，我搜了一下似乎是 PORT 配置有问题？

> 第十步：发件服务器设置如下图，设置完点击“返回”。
SMTP发件服务器地址：smtp.yeah.net 安全：开（SSL/TLS） 端口号：465 / 994
注：1、126邮箱的SMTP服务器地址：smtp.126.com ，163邮箱的SMTP服务器地址：smtp.163.com；
2、若安全选择关闭，请将端口号改为 25。
> http://wap.yeah.net/xm/static/html/yeah_symbian_2.html

**Comment by dyxang** [comment]
> 才发现原来你截了配置图了，我搜了一下似乎是 PORT 配置有问题？换 465 或者 994 试一下呢？
> > 2、若安全选择关闭，请将端口号改为 25。

天啊，原来我 Leancloud 一直设置错的但是也可以用。
不过因为总是莫名其妙被判定为垃圾邮件，我刚刚换成了 Yandex 的，正常是正常了，但是邮件通知又没得了
![](https://i.loli.net/2020/12/17/gCpr6TzSmVs2X7Y.jpg)
是不是那个邮箱密码的变量不能设置成 secret 啊，还是 SERVICE 值的问题

**Comment by lizheming** [comment]
有可能之前你没配置 `SECURE=true`？ Yandex 这个，你是不是 USER 和 PASS 配反了啊…为啥把  USER 打了马赛克？

**Comment by dyxang** [comment]
> 有可能之前你没配置 `SECURE=true`？ Yandex 这个，你是不是 USER 和 PASS 配反了啊…为啥把 USER 打了马赛克？

变量名：SMTP_SECURE 值：true 没错啊，user 和 pass 没有配反，邮箱怕 spam

**Comment by lizheming** [comment]
`SMTP_SECURE = true` 表示开启安全连接，按照文档所说应该是要使用 465 或者 994 端口的。通知邮件这个具体你自己调一下吧，其实就是下面几个变量配置，waline 这块也没做什么的。之后我再把这块的日志信息输出一下，方便排查问题吧。

https://github.com/lizheming/waline/blob/42ccb3ab377422fcf038dec898c00caa82c652da/packages/server/src/service/notify.js#L8-L22

**Comment by dyxang** [comment]
目前把 那个 SMTP_PASS 的类型由 secret 改为了 Plaintext 就能够报错了，我寻思我填的也是登陆密码啊，结果又报错
```
2020-12-17T14:22:42.443Z	
Mail send fail: Error: Invalid login: 535 5.7.8 Error: authentication failed: This user does not have access rights to this service
    at SMTPConnection._formatError (/var/task/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
    at SMTPConnection._actionAUTHComplete (/var/task/node_modules/nodemailer/lib/smtp-connection/index.js:1513:34)
    at SMTPConnection.<anonymous> (/var/task/node_modules/nodemailer/lib/smtp-connection/index.js:540:26)
    at SMTPConnection._processResponse (/var/task/node_modules/nodemailer/lib/smtp-connection/index.js:932:20)
    at SMTPConnection._onData (/var/task/node_modules/nodemailer/lib/smtp-connection/index.js:739:14)
    at TLSSocket.SMTPConnection._onSocketData (/var/task/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9) {
  code: 'EAUTH',
  response: '535 5.7.8 Error: authentication failed: This user does not have access rights to this service',
  responseCode: 535,
  command: 'AUTH PLAIN'
}

```

**Comment by dyxang** [comment]
问题解决，根本问题是在 Yandex 邮箱配置上。因为网上的基本上没有提到 Yandex 如何配置 SMTP 的用户名，而且一般情况都是直接填邮箱，但恰恰 **Yandex 一般情况不是填邮箱**！我找了 Yandex mail 的文档才解决问题。解决办法及其他补充如下：

-  在 `Yandex Mail All settings → Email clients` 下依次勾选 `Use a mail client to retrieve your Yandex mail>From the imap.yandex.com server via IMAP>IMAP authorization method>App passwords and OAuth tokens`
- 然后到[这个页面](https://passport.yandex.com/profile/access)创建单独密码，当然你要不介意安全问题也可以直接勾选 `IMAP authorization method>Portal password`


- **利用Yandex搭建个人域名邮箱服务的**，填个人域名全称，比如`a@example.com`；**仅仅注册 Yandex 邮箱服务的**，填邮箱`@`之前的名称，比如若你的邮箱是 `xiaoming@yandex.com` 那么就填 `xiaoming`
-  必要：启用 **SMTP_SECURE** 为 `true`，端口为465

[Yandex 文档](https://yandex.com/support/mail/)
