### ISSUE TITLE
数据迁移助手无法转换较大数据文件

### ISSUE THREAD

**Issue by penndu** [lizheming/waline#77]
目前有一个1.12M评论文件，无法转换为sql模式，复制进去后点转换，持续没有反应！

**Comment by lizheming** [comment]
可以看一下浏览器控制台是否有什么报错，并邮件提供下你的评论文件吗？我的邮箱在个人资料里有。

**Comment by lizheming** [comment]
已邮件收到你的导出文件。看了下应该是导出文件格式有问题，不太清楚你这个 Valine 的数据文件是从哪里导出的，但我这边看到的是你的数据不是一个 JSON。帮你修改了下格式邮件发回给你了，我这边试了下修改后的是可以转换的，你试一下吧。
