### ISSUE TITLE
转换后的文件出现乱码，且无法导入MySQL！

### ISSUE THREAD

**Issue by penndu** [lizheming/waline#79]
详见截图！
![Snipaste_2020-12-20_02-11-36.jpg](https://7.dusays.com/2020/12/20/069a866276fd9.jpg)

![Snipaste_2020-12-20_02-13-41.jpg](https://7.dusays.com/2020/12/20/ae7f09fad366d.jpg)

**Comment by lei2rock** [comment]
不要用Excel打开，会乱码，换成vsc什么的打开就没事。我是这样操作的，phpmyadmin导入时候把第一行删了（vsc打开编辑），同时要填写导入字段顺序（第一行）。

**Comment by penndu** [comment]
照着做了，还是导入失败~

**Comment by lizheming** [comment]
使用 Excel 打开是乱码是正常的现象，原因是 Excel 需要 GBK 编码。如果 CSV 导入失败请提供下失败的报错信息吧。

**Comment by penndu** [comment]
我录了段操作动图~

![Honeycam 2020-12-20 23-36-07.gif](https://7.dusays.com/2020/12/20/4d2a0c0970664.gif)

**Comment by lizheming** [comment]
- [x] LeanCloud 国内版导出文件格式不对前无法转换
- [x] 转换数据第一条丢失
- [x] 转换数据导入提示 `rid` 和 `pid` 字段报错
- [x] 转换数据丢失 IP 字段

针对 MySQL 导出反馈的以上问题应该都已修复，可以再确认下。
