### ISSUE TITLE
有计划支持多种存储方式吗？

### ISSUE THREAD

**Issue by eallion** [lizheming/waline#8]
比如阿里云表格存储、腾讯云开发、AWS DynamoDB

**Comment by lizheming** [comment]
有的，后期会把要把存储提升，目前还在堆功能😅

**Comment by eallion** [comment]
优先级高吗？

**Comment by lizheming** [comment]
需要等做完文章阅读统计和后台评论管理再做它，因为这几个功能都会增加很多的表操作，欢迎一块来开发呀😉

**Comment by eallion** [comment]
我不太擅长这个，我只会 CRUD 。但是我尽量提供帮助。

**Comment by lizheming** [comment]
OK 没事呀，我可以搭架子，我尽快把数据方法抽象的搞定，然后你可以帮忙添加多平台的支持

**Comment by lizheming** [comment]
目前除了 LeanCloud, 已增加 MySQL, MongoDB, SQLite, PostgreSQL 多种数据库的支持，并支持扩展其它存储服务。具体可见文档 https://waline.js.org/databases.html 欢迎一块来增加更多的存储服务支持呀~
