### ISSUE TITLE
无法通过评论管理页面直接跳转

### ISSUE THREAD

**Issue by penndu** [lizheming/waline#80]
详见截图~

![Snipaste_2020-12-20_15-24-55.jpg](https://7.dusays.com/2020/12/20/f585e7cfbd5ee.jpg)

**Comment by lizheming** [comment]
我试了截图左下角的链接是可以直接打开你的文章地址的，如果是想要反馈有多个 / 的问题的话，可以把 SITE_URL 配置中末尾的 / 去掉试一下，不过这个不影响链接的跳转哈。

**Comment by penndu** [comment]
docker run -d --restart=always -e LEAN_ID=xxx -e LEAN_KEY=xxx -e LEAN_MASTER_KEY=xxx -e LEAN_SERVER=https://a.dusays.com -e SITE_NAME=杜老师说 -e SITE_URL=https://dusays.com -e IPQPS=0 -e SECURE_DOMAINS=dusays.com -e AUTHOR_EMAIL=xxx -e SMTP_SERVICE=QQ -e SMTP_USER=xxx -e SMTP_PASS=xxx -e SC_KEY=xxx -p 8360:8360 lizheming/waline

以上是我运行命令，我试过了，如果多一个/，waline会判断为新页面~

**Comment by penndu** [comment]
错误演示~

![Honeycam 2020-12-20 23-56-49.gif](https://7.dusays.com/2020/12/20/da7d6cde51763.gif)

**Comment by lei2rock** [comment]
确实不会跳转，只会了解到有评论的文章页，而且地址是这样的格式 `https://blog.dlzhang.com//posts/30/`，我 `SITE_URL` 配置中末尾没有`/`

**Comment by lizheming** [comment]
如果是要跳转到评论具体的锚点的话目前是没有处理的，主要的原因是评论是动态加载的，不好利用浏览器的锚点定位的方式去做。

**Comment by penndu** [comment]
> 如果是要跳转到评论具体的锚点的话目前是没有处理的，主要的原因是评论是动态加载的，不好利用浏览器的锚点定位的方式去做。

不需要跳转到评论具体锚点，只需要跳转到评论页面即可！

**Comment by lei2rock** [comment]
> > 如果是要跳转到评论具体的锚点的话目前是没有处理的，主要的原因是评论是动态加载的，不好利用浏览器的锚点定位的方式去做。
> 
> 不需要跳转到评论具体锚点，只需要跳转到评论页面即可！

是的，能跳转到评论页就行。当然能跳转到锚点的话最好。另外，只要链接带上评论页的锚点，页面加载以下代码就可以跳转到锚点了

```js
<script type="text/javascript">
if(window.location.hash){
    var checkExist = setInterval(function() {
        if ($(window.location.hash).length) {
            $('html, body').animate({scrollTop: $(window.location.hash).offset().top-90}, 1000);
            clearInterval(checkExist);
        }
    }, 100);
}
</script>
```

**Comment by lizheming** [comment]
刚才点开你的动图去看了一下，原来是说提早跳转的地址 `//301/` 多带了 `/` 导致跳转过去之后无法正确获取到评论。这块我处理一下吧，稍等。

**Comment by lizheming** [comment]
@waline/admin@0.2.4 发布，删除了多余的 `/` ，清一下浏览器缓存再试试吧。

**Comment by penndu** [comment]
> @waline/admin@0.2.4 发布，删除了多余的 `/` ，清一下浏览器缓存再试试吧。

docker部署的如何更新？

**Comment by lizheming** [comment]
这个是前端的更新，你清下浏览器缓存就可以了。

**Comment by penndu** [comment]
> 这个是前端的更新，你清下浏览器缓存就可以了。

好的，已经成功跳转！
