### ISSUE TITLE
[Feature Request] Artalk 数据导入

### ISSUE THREAD

**Issue by jalenchuh** [lizheming/waline#81]
请问可否支持 [Artalk](https://github.com/qwqcode/Artalk) 的数据导入

**Comment by lizheming** [comment]
可以的话可以提供一份 Artalk 的 JSON 存储文件给我，我做下兼容试试。

**Comment by jalenchuh** [comment]
已经发送至你的邮箱

**Comment by lizheming** [comment]
按照你给的范例文档迁移工具增加了 Artalk 数据转换的支持， https://waline.js.org/migration/tool.html 你可以试试，把 `comments.data.json` 文件的数据粘贴进去应该就可以了。

**Comment by jalenchuh** [comment]
@lizheming 刚刚尝试了数据导入，导入完成后，网站上显示不出评论（但评论基数是正常的），而且后台直接变成空白

![image.png](https://7.dusays.com/2020/12/27/2e4878ace408c.png)

**Comment by lizheming** [comment]
Waline 的 serverURL 提供一下，我去看一下错误信息吧。

**Comment by jalenchuh** [comment]
https://api.jalenchuh.cn/waline

**Comment by lizheming** [comment]
带二级目录的域名目前还有很多地方有适配的问题，个人建议你直接使用例如 `https://waline.jalenchuh.cn` 这样的二级域名碰到问题的概率会小一点。

**Comment by jalenchuh** [comment]
不是二级目录的问题，前面没用二级目录的时候就有这个问题，刚刚才改成了二级目录。

**Comment by lizheming** [comment]
你先改回去，我再看看

**Comment by jalenchuh** [comment]
https://api.jalenchuh.cn/

**Comment by lizheming** [comment]
我粗看了下似乎没看出什么问题来，你方便的话加下用户群，进群聊一下我了解下其它信息吧。

**Comment by jalenchuh** [comment]
已加
