### ISSUE TITLE
Vercel初始化后打开网址页面内容为空

### ISSUE THREAD

**Issue by fnoopv** [lizheming/waline#82]
部署时间：12月21号
按照教程部署后，点击Visit打开页面，评论窗口闪一下就消失
按F12看console报错
![image](https://user-images.githubusercontent.com/24599198/102720042-c2c14480-432c-11eb-8261-aa1e6cca7d94.png)

**Comment by yvesyc** [comment]
需要在 Environment Variables 初配置 LEAN_ID, LEAN_KEY 和 LEAN_MASTER_KEY 三个环境变量。

**Comment by fnoopv** [comment]
添加了，但是就是不行，，我Redeploy了一下好了

**Comment by yeung66** [comment]
我也遇到了这个问题，返回信息为
```json
{"errno":500,"errmsg":"Not initialized"}
```

**Comment by lizheming** [comment]
@yeung66 新开个 issue 吧，说下你是如何部署的。

**Comment by Waterkuiiiiii** [comment]
我也.....你们怎么解决的？

**Comment by lizheming** [comment]
@Waterkuiiiiii 配环境变量重新部署一下

**Comment by Simple2ich4n** [comment]
我也遇到这个问题，我没有仔细看文档，变量名错写了，可以注意下
