### ISSUE TITLE
最新评论挂件调用无效

### ISSUE THREAD

**Issue by penndu** [lizheming/waline#84]
![Snipaste_2020-12-21_20-47-21.jpg](https://7.dusays.com/2020/12/21/30b4ce376c55c.jpg)

![Snipaste_2020-12-21_20-46-54.jpg](https://7.dusays.com/2020/12/21/4885d7d6aae4b.jpg)

![Snipaste_2020-12-21_20-47-59.jpg](https://7.dusays.com/2020/12/21/8b7f17d0e66d9.jpg)

**Comment by penndu** [comment]
用的是Volantis主题，该主题已集成了waline，调用代码写在了footer.ejs

![Snipaste_2020-12-21_20-51-26.jpg](https://7.dusays.com/2020/12/21/707082d80a62f.jpg)

配置文件如下

![Snipaste_2020-12-21_20-52-59.jpg](https://7.dusays.com/2020/12/21/30ab4b889664d.jpg)

**Comment by jerryc127** [comment]
你可以f12 看看控制台报什么错

**Comment by penndu** [comment]
> 你可以f12 看看控制台报什么错

没报任何错误~

**Comment by jerryc127** [comment]
網站發來看看

**Comment by penndu** [comment]
> 網站發來看看

网址是dusays.com

**Comment by jerryc127** [comment]
你試下改成
window.addEventListener('load'

你的配置沒問題

**Comment by penndu** [comment]
```
    <script>
    window.addEventListener('load', function() {
      Waline.Widget.RecentComments({
        el: '#waline-recent',
        serverURL: 'https://n.dusays.com',
        count: 10
      });
    });
    </script>
```
这样的吗？

**Comment by jerryc127** [comment]
嗯
你的问题估计是没运行到/或者 运行前 你的waline 没有加载到

load 是window.addEventListener 不是 document.addEventListener

**Comment by lizheming** [comment]
你需要把 `Waline.Widget.RecentComments()` 这个放在 `waline.js` 的后面

**Comment by penndu** [comment]
> ```
>     <script>
>     window.addEventListener('load', function() {
>       Waline.Widget.RecentComments({
>         el: '#waline-recent',
>         serverURL: 'https://n.dusays.com',
>         count: 10
>       });
>     });
>     </script>
> ```
> 
> 这样的吗？

用这样的方式生效，不过排版不是特别好看~

**Comment by jerryc127** [comment]
> > ```
> >     <script>
> >     window.addEventListener('load', function() {
> >       Waline.Widget.RecentComments({
> >         el: '#waline-recent',
> >         serverURL: 'https://n.dusays.com',
> >         count: 10
> >       });
> >     });
> >     </script>
> > ```
> > 
> > 
> > 这样的吗？
> 
> 用这样的方式生效，不过排版不是特别好看~

是的 UI自己调
返回的是评论数组
自己提取想要的资料

**Comment by penndu** [comment]
> > > ```
> > >     <script>
> > >     window.addEventListener('load', function() {
> > >       Waline.Widget.RecentComments({
> > >         el: '#waline-recent',
> > >         serverURL: 'https://n.dusays.com',
> > >         count: 10
> > >       });
> > >     });
> > >     </script>
> > > ```
> > > 
> > > 
> > > 这样的吗？
> > 
> > 
> > 用这样的方式生效，不过排版不是特别好看~
> 
> 是的 UI自己调
> 返回的是评论数组
> 自己提取想要的资料

非常感谢您的帮助~
