### ISSUE TITLE
server/src/controller/index.js错误

### ISSUE THREAD

**Issue by YiHui-Liu** [lizheming/waline#85]
该文件中serverURL的值是serverURL: location.protocol + '//' + location.host + location.pathname.slice(1)，如果当前url是https://waline.vercel.app/ui/login，那就会返回https://waline.vercel.appui/login，导致请求错误
（问题出现于Nginx反向代理目录

**Comment by lizheming** [comment]
@waline/vercel@0.15.0 已修复该问题，你可以之后更新下镜像再试试~
