### ISSUE TITLE
vercel 部署后打开页面空白，返回的请求提示 Not initialized

### ISSUE THREAD

**Issue by yeung66** [lizheming/waline#89]
我是从 valine 迁移过来的，因而直接使用了此前国际版 leancloud 的 appid 和 appkey。

按照 vercel 部署的[步骤](https://waline.js.org/quick-start.html#vercel-%E9%83%A8%E7%BD%B2) 进行部署并且成功部署，但是点击进去后页面空白，打开开发者管理工具反向请求返回响应全是 500

```json
{"errno":500,"errmsg":"Not initialized"}
```

有想过是不是 leancloud 的域名安全限制，但把部署好的 serverURL 添加上去还是不行。

我部署后的地址为 [https://waline-pi.vercel.app/](https://waline-pi.vercel.app/) 登录注册功能也不行。

**Comment by lizheming** [comment]
有配置 LEAN_MASTER_KEY 吗？

**Comment by yeung66** [comment]
> 有配置 LEAN_MASTER_KEY 吗？

疏忽了，我以为国际版不用这个环境变量，我去试试

**Comment by yeung66** [comment]
好了，感谢回复！

**Comment by owenyk** [comment]
> 
请问这些在settings/environment-variables页面没有那三个veline配置选项输入框啊，只有name和value，请问是填在那？

**Comment by ChengyangHu** [comment]
感谢，已解决

**Comment by along-h** [comment]
> 有配置 LEAN_MASTER_KEY 吗？

为什么我部署了也不行

**Comment by Yelelalearn** [comment]
> > 
> 
> 请问这些在settings/environment-variables页面没有那三个veline配置选项输入框啊，只有name和value，请问是填在那？

你好，你解决了吗
