### ISSUE TITLE
serverURL option is required for apps from CN 

### ISSUE THREAD

**Issue by gadzan** [lizheming/waline#9]
按照文档在Vercel 部署后, 会出现下面错误
```
TypeError: serverURL option is required for apps from CN 
```

我已经在Vercel 设置了环境变量 LEAN_SERVER:  xxxxxxx.vercel.app

但还是有这个错误. 请问还有哪里需要设置才能避免这个错误吗?

**Comment by eallion** [comment]
`LEAN_SERVER` 域名是 LeanCloud 后面的 API 域名，不是 Vercel 的域名。

**Comment by lizheming** [comment]
@gadzan 如果你是使用了 LeanCloud 国内版的话，需要设置 `LEAN_SERVER` 值是你在 leancloud 后台绑定的备案域名。如果你是使用的 LeanCloud 国际版的话，是不需要绑定这个环境变量的，如果有的话你的这个值如楼上所说是有问题的可能也会有问题。

如果你是没有配置过 `LEAN_SERVER` 而且用的是 LeanCloud 国际版还出现了这个问题，可以看一下你的仓库的这个文件 https://github.com/lizheming/waline/blob/master/example/package.json#L5 `@waline/vercel` 应该是 `0.5.0` 的，如果不是你改成这个应该就可以了。

https://leancloud.cn 是 LeanCloud 国内版，https://leancloud.app 是 LeanCloud 国际版。

**Comment by gadzan** [comment]
感谢两位大佬, 原因是@waline/vercel的版本太低了, 之前用的是0.1.0, 现在改成0.5.0就可以了. 可能是淘宝源默认安装的是0.1.0的.

我用的是国内版, 域名也绑定了, 之前以为LEAN_SERVER的值不对, 一直在换. 所以感觉是不是我理解错了, 误认为应该是vercel.app的域名. 

域名改回绑定的域名, 依赖升到最新, 问题就解决了, 谢谢.

**Comment by lizheming** [comment]
@gadzan 是的 Vercel 似乎会有 cache 不会按照 semver 找到最新，所以用之前的模板创建的似乎都有点问题，我这边之前已经将模板的依赖版本号升级到最新了，之后创建的话不会有这个问题了。
