### ISSUE TITLE
电报机器人都有了，Qmsg酱能期待一下吗？

### ISSUE THREAD

**Issue by CCKNBC** [lizheming/waline#90]
电报机器人都有了，Qmsg酱能期待一下吗？
（要是云函数能访问电报就好了，只好换vercel）

**Comment by lizheming** [comment]
哈哈，我觉得也不是不行，等哪位可爱的小伙伴帮忙加下吧~

**Comment by lei2rock** [comment]
添加了「Qmsg酱」为QQ好友，一直没有同意，测试不了23333

看了一下，Qmsg 酱通知可以参考这个 https://github.com/W4J1e/Hexo-Valine-ASPush/blob/master/utilities/send-mail.js

**Comment by lei2rock** [comment]
Qmsg 酱通知已经提交 PR，欢迎测试～

**Comment by CCKNBC** [comment]
赞 @lei2rock

**Comment by lizheming** [comment]
@waline/vercel@0.16.0 已发布
