### ISSUE TITLE
LeanCloud导出的文件，经过转换后无法导入MySQL~

### ISSUE THREAD

**Issue by penndu** [lizheming/waline#97]
LeanCloud导出的文件如下：

[wJcVJsqnwT03uf1gALFs1ivr-gzGzoHsz-exporttoLhenH38120778464409317.tar.gz](https://github.com/lizheming/waline/files/5745662/wJcVJsqnwT03uf1gALFs1ivr-gzGzoHsz-exporttoLhenH38120778464409317.tar.gz)

报错内容如下：

![Snipaste_2020-12-28_10-20-47](https://user-images.githubusercontent.com/46226528/103185221-62b33b00-48f6-11eb-896a-8f3001cf4f72.jpg)

**Comment by penndu** [comment]
希望可以将转换后的SQL文件发我，非常感谢！

**Comment by lizheming** [comment]
[waline_2020-12-28.sql.zip](https://github.com/lizheming/waline/files/5747365/waline_2020-12-28.sql.zip)

**Comment by penndu** [comment]
> [waline_2020-12-28.sql.zip](https://github.com/lizheming/waline/files/5747365/waline_2020-12-28.sql.zip)

非常感谢！
